### ISSUE TITLE
Cant use Tilix after uninstalling fish

### ISSUE THREAD

**Issue by jsquardo** [gnunn1/tilix#1585] opened 2018-11-28 21:19 UTC
I installed fish on Ubuntu 18.04 KDEneon. I made it my main shell. I later uninstalled fish and now whenever I open Tilix I get "Failed to execute child process "/usr/bin/fish" no such file or directory. 

I can use Konsole just fine now in bash but Tilix wont work. Even tried changing profiles.

**Comment by gnunn1** [comment] 2018-11-28 21:22
I don't support KDE and so I'm not sure what the issue is. However obviously something thinks you are still using fish. Did you configure your profile to directly use /usr/bin/fish in the profile command tab per chance?

**Comment by FFY00** [comment] 2018-11-28 21:46
Did you properly change your shell with chsh?

**Comment by jsquardo** [comment] 2018-11-28 22:52
> I don't support KDE and so I'm not sure what the issue is. However obviously something thinks you are still using fish. Did you configure your profile to directly use /usr/bin/fish in the profile command tab per chance?

Yea I changed it do use /bin/bash just to see but then I get the pop up error when I open terminal.

**Comment by jsquardo** [comment] 2018-11-28 22:52
> Did you properly change your shell with chsh?

Yea. It works in Konsole just not Tilix :(

**Comment by gnunn1** [comment] 2018-12-22 18:33
Sorry I have no clue what the issue is, I'm closing the issue because I don't think it it's a tilix issue. You could try uninstalling tilix and re-installing it to see if that helps just to reset the settings.

**Closed by gnunn1** 2018-12-22 18:33 UTC

**Comment by lucidyan** [comment] 2019-06-24 11:42
@jsquardo I think you forgot to change your default console to bash after uninstalling fish. Try that next time:
`sudo chsh -s /bin/bash username`
