### ISSUE TITLE
Hyperlinks only work until I run an application in shell

### ISSUE THREAD

**Issue by saivert** [gnunn1/tilix#956] opened 2017-06-03 12:30 UTC
I start up Tilix, paste an URL into the shell. The URL is now clickable and works.
I launch a second shell. Now clicking URL shows error message: Could not open match ''

Versions
	Tilix version: 1.5.8
	VTE version: 0.48
	GTK Version: 3.22.15

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

**Comment by gnunn1** [comment] 2017-06-03 12:35
Is this a duplicate of #952?

**Comment by saivert** [comment] 2017-06-03 12:37
So this is fixed in master?

**Comment by gnunn1** [comment] 2017-06-03 12:38
Yes

**Closed** 2017-06-03 12:40 UTC
