### ISSUE TITLE
Lines change font weight when hovered

### ISSUE THREAD

**Issue by wezm** [gnunn1/tilix#1440] opened 2018-06-14 04:54 UTC
I'm seeing a strange issue in Tilix. It started a couple of versions ago (I can dig up the specific version if need be). Often lines get rendered at a heavier weight when the mouse goes over them and the when it goes over them again they change back to normal.

[You can see the behaviour in this this short video](https://imgur.com/a/stNqk5N). Note that there are a couple of lines that start out bolder then change when the cursor goes over them.

Here is a screen shot. The lines shown here should all be the same weight/color.

![screenshot from 2018-06-14 14-47-48](https://user-images.githubusercontent.com/21787/41392119-0a4f9b24-6fe2-11e8-855d-198ee7e7979b.png)

Note that it doesn't happen in GNOME Terminal and only seems to happen with PragmataPro Mono in size 12. Size 11 and 13 did not exhibit the behaviour. Nor did Space Mono.

**OS:** Arch Linux
**DE:** Stock GNOME, default theme
**Display Server:** Xorg
**Font:** PragmataPro Mono 12
**Tilix Version:** 1.8.1 installed from Arch main repos

**Comment by gnunn1** [comment] 2018-06-14 11:51
No idea what could be causing this off-hand, it looks like as the mouse goes over the individual lines get re-painted but use dim colors for some reason. Do you have dimming enabled in tilix, try disabling it and see if it makes any difference. Are not using something that auto focuses a window as the mouse passes over it?

**Comment by egmontkob** [comment] 2018-06-14 17:16
No idea here either. I'm not aware of such a bug in VTE.

I'm wondering if it could be related to transparency, and the same glyph being drawn twice (hence becoming whiter)...?

Could you please repeat the same, having some dense glyph (like U+2588 █) in the command line too, so that we can examine the exact color (without antialiasing)?

**Comment by wezm** [comment] 2018-06-15 00:00
> Do you have dimming enabled in tilix, try disabling it and see if it makes any difference. Are you using something that auto focuses a window as the mouse passes over it?

No none of this

![screenshot from 2018-06-15 09-17-17](https://user-images.githubusercontent.com/21787/41442903-10866748-707d-11e8-9c5e-8554783fe1e1.png)

I have a custom colour scheme and also use [base16-shell](https://github.com/chriskempson/base16-shell).

> Could you please repeat the same, having some dense glyph (like U+2588 █) in the command line too, so that we can examine the exact color (without antialiasing)?

![image](https://user-images.githubusercontent.com/21787/41442991-abd21990-707d-11e8-94e2-cf0740d34db3.png)

I doesn't seem to affect the block character.

My font settings in GNOME Tweak Tool are as follows:

![image](https://user-images.githubusercontent.com/21787/41443028-d7d9dfaa-707d-11e8-92d8-cc181e5d6bae.png)

It still happens with hinting set to None and Full.

**Comment by egmontkob** [comment] 2018-06-16 22:05
Background color is hex 18, foreground is hex D8 (grayscale, so R, G, B channels all have the same value).

Let's try to do a bit of math: What would happen to a pixel of color `x` (within the 18 .. D8 range) at the antialiased edge of a letter, if the letter was accidentally painted twice?

When it's first printed, on background 18 the foreground D8 is applied with a certain alpha (`a` between 0 and 1), resulting in color `x`, that is:

    x = a * D8 + (1-a) * 18

so

    a = (x-18) / C0

Then again D8 is applied on the top of `x` with alpha `a`, resulting in color `y`:

    y = a * D8 + (1-a) * x

So, for example, the upper-left corner of the upper-left letter "v" in the first screenshot is color 38, which, if printed twice, can be computed by this being fed into `bc -l`:

    obase=16
    ibase=16
    x=38
    a = (x-18) / C0
    y = a * D8 + (1-a) * x
    y

telling us the result 52.AAA (funny to see hexadecimal fractions), and the upper-left of the letter "v" one line below is of color hex 52.

I've verified at a couple of other points that the pixels of the bolder vs. narrower variants indeed match the above formula. So I believe this assumption is justified: The text is printed twice on each other.

I guess it's time to dig deeper into that draw signal hijacking stuff that I believe Christian implemented in VTE for Tilix to use (does Tilix already use that one?)...

**Comment by egmontkob** [comment] 2018-06-16 22:10
@wezm What's the version of your VTE? You seem to have an up-to-date Arch, so I believe this should be 0.52.x, but let's have it confirmed.

**Comment by wezm** [comment] 2018-06-17 01:31
> What's the version of your VTE?

Yep 0.52.2:

```
$ pacman -Qi vte3
Name            : vte3
Version         : 0.52.2-1

```

**Comment by gnunn1** [comment] 2018-06-23 13:30
This being tracked upstream in the VTE issue list so closing this since it's not a tilix specific bug.

**Closed by gnunn1** 2018-06-23 13:30 UTC

**Comment by egmontkob** [comment] 2019-05-04 14:05
Finally I can reproduce this, so expect a fix soon. Please follow vte/4 for progress and patches to test.

**Comment by egmontkob** [comment] 2019-05-05 22:28
@wezm Could you please test the patch from https://gitlab.gnome.org/GNOME/vte/issues/4 ?

**Comment by wezm** [comment] 2019-05-07 03:35
@egmontkob Sorry I changed jobs and no longer have the machine that was exhibiting the problem. Thanks for working on a fix though.

**Comment by egmontkob** [comment] 2019-07-09 15:32
We believe that vte 0.56.3 fixes this issue.
