### ISSUE TITLE
Issue with text selection in git log

### ISSUE THREAD

**Issue by lburgazzoli** [gnunn1/tilix#881] opened 2017-04-13 14:55 UTC
When using git log I noticed that the selection flickers and I cannot select text:
 
![peek 2017-04-13 16-38](https://cloud.githubusercontent.com/assets/1868933/25010196/a76f59d6-2069-11e7-9b51-0ea561d8b57f.gif)

This does not happens with other terminal like gnome-terminal.

My .gitconfig is pretty simple, like:

```
[push]
    default = simple
[core]
    autocrlf = input
    editor = vim
[color]
    ui = auto
[color "branch"]
    current = yellow reverse
    local = yellow
    remote = green
[color "diff"]
    meta = yellow bold
    frag = magenta bold # line info
    old = red # deletions
    new = green # additions
[color "status"]
    added = yellow
    changed = green
    untracked = cyan
```

**Comment by gnunn1** [comment] 2017-04-13 22:49
I cannot reproduce this as it works fine for me. I tried your .gitconfig and I don't get the same issue. I tried ```git log``` on the terminix project and saw no issue. I'm wondering if this could be caused by an escape code or some other peculiarity in the output, do you get the same issue with other git projects?

BTW, if you are working on Camel keep up the good work, I love that project!

**Comment by gnunn1** [comment] 2017-04-13 22:51
Although if it was a problem with an escape code you should see the same issue in gnome-terminal since both use the VTE. What distro and version are you using?

**Comment by lburgazzoli** [comment] 2017-04-14 06:41
It behaves the same for any git project and only in tilix (no issues in gnome-terminal/terminator) that's why I'm a little puzzled.

I'm on Fedora 25 Cinnamon.

BTW1, I'm using https://github.com/chriskempson/base16-shell with Monokay theme
BTW2, yeah I'm a Camel PMC :)

**Comment by lburgazzoli** [comment] 2017-04-14 08:08
I forgot to mention that the issue happens only when git log paginates and in that case I also noticed that tilix + xorg are quire resource consuming:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
 2021 root      20   0  501312  42632  27800 S  42.5  0.4   6:36.79 Xorg                                                                                                         
26159 xxxxxxxx  20   0  759164  53048  37472 S  24.6  0.4   1:55.31 tilix                     
```

**Comment by gnunn1** [comment] 2017-04-16 14:56
@lburgazzoli Does this happen when using vim outside of ```git log``` or just for ```git log```?

The other thing you can try though I doubt it's the cause, is to run Tilix without DBus Activation since that's one of the few differences between tilix and gnome-terminal. To do so, open gnome-terminal without tilix running and run tilix at the command line, i.e. ```tilix```. Then try your ```git log``` and see if you get the same behavior.

**Comment by gnunn1** [comment] 2017-04-16 15:17
Also, one other thing to try. There is a hidden dconf switch called ```enable-transparency``` in com/gexperts/Tilix. Try setting it to false and see if that makes any difference as well.

**Comment by egmontkob** [comment] 2017-04-16 20:51
Could, by any chance, your Tilix use a different VTE than gnome-terminal? What does `echo $VTE_VERSION` say? VTE had such a bug for a short time in the devel series about a year ago, see https://bugzilla.gnome.org/show_bug.cgi?id=762446.

**Comment by gnunn1** [comment] 2017-04-16 20:56
@egmontkob Seems pretty unlikely, but I guess you never know. @lburgazzoli Could you run the command ```tilix --version``` and post it here. That will show the tilix, VTE and GTK versions you are using.

**Comment by gnunn1** [comment] 2017-04-16 21:13
Also, @lburgazzoli when you say it only happens when you paginate, are the steps you are doing to reproduce this:

* run ```git log```
* hit spacebar a few times to switch pages
* try to select text using the mouse

I tried the above and couldn't reproduce, but maybe if you post the exact steps if it differs from what I have here I could get lucky and reproduce it.

**Comment by egmontkob** [comment] 2017-04-16 21:21
Could be due to cropping, but `less`'s status bar is not present in the screenshot. Makes me wonder if maybe no pager is used and git directly writes to the terminal.

**Comment by lburgazzoli** [comment] 2017-04-18 05:39
@gnunn1 

Here's ```tilix--version``` output:

```
Versions
	Tilix version: 1.5.4
	VTE version: 0.46
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```
Here's the list of packages related to vte:

```
vte-0.28.2-18.fc25.x86_64
vte-profile-0.46.1-1.fc25.x86_64
vte291-0.46.1-1.fc25.x86_64
libvterm-0-0.1.bzr681.fc25.x86_64
vte3-0.36.5-2.fc24.x86_64
```

I did reset tilix to its defaults and then followed the steps you mentioned and same issue happens, it does not happens on a vm I spin up for testing this issue so there's should something wrong in my setup but I can't figure it out.

**Comment by lburgazzoli** [comment] 2017-04-24 10:17
Looks like the issue is caused by the following thing:

```
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
```
I've removed it  (while keeping "use login shell") and now it seems to work as expected.

**Comment by gnunn1** [comment] 2017-04-25 00:44
@lburgazzoli I wonder if the issue is the two combined together such that vte.sh get's sourced twice? The idea is that you should only need to do one or the other. Anyway, I tested it with login shell enabled and vte sourced and still can't reproduce it.

I'm thinking we should just close this issue and chalk it up as one of life's oddities, I don't plan on spending any time tracking it down further now that you have a solution. Let me know if that's OK or just close the issue.

**Closed** 2017-04-25 08:49 UTC
Labels: bug, Can't Reproduce

**Comment by anthrotype** [comment] 2017-10-02 10:26
I found that disabling `-X` option that git by default sends to `less` pager solves the flickering issue while selecting text inside `git log`.
This is what I did:

```bash
git config --global --replace-all core.pager 'less -+X'
```

I am not quite sure what `-X` option is meant to do.

https://linux.die.net/man/1/less

> -X or --no-init
> Disables sending the termcap initialization and deinitialization strings to the terminal. This is sometimes desirable if the deinitialization string does something unnecessary, like clearing the screen

Anyway, this worked for me.

**Comment by egmontkob** [comment] 2017-10-02 12:23
I'm wondering if this could be related to #1122. The logical window size continuously changing back and forth would cause tons of WINCH sent to less, which in turn repaints its screen which invalidates the mouse selection??

@anthrotype Could you please try disabling Preferences -> Appearance -> Use overlay scrollbar? If that helps, the latest Tilix (from git) should fix the problem for you.

**Comment by anthrotype** [comment] 2017-10-02 12:36
Yay! That fixed it :+1: 
Thank you so much! :smile:
