### ISSUE TITLE
saved json layouts that contain commands not working

### ISSUE THREAD

**Issue by cazacugmihai** [gnunn1/tilix#1128] opened 2017-09-21 08:55 UTC
This one is related to https://github.com/gnunn1/tilix/issues/1081.

I have used the layout specified by @sarlindo and the output (for both panels) is:

> The child process was aborted. [Relaunch]

Environment:
```
Versions
	Tilix version: 1.6.4
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

Ubuntu 16.04.3
```

**Comment by gnunn1** [comment] 2017-09-22 17:26
Duplicate of #1081

**Comment by cazacugmihai** [comment] 2017-09-22 18:52
Yes, I have mentioned that it is related to #1081 but that issue is already closed and the problem still exists.

**Comment by cazacugmihai** [comment] 2017-09-28 12:56
Can you reopen this issue, please?

**Comment by gnunn1** [comment] 2017-09-28 13:11
Have you tried master, that is where the issue should be fixed. I haven't pushed a new version out that fixes it beyond 1.6.4. If it's still broken in master I'm happy to re-open it, you should be able to re-open it as well though if needed.

**Comment by cazacugmihai** [comment] 2017-09-28 13:36
No, I've not tried the master at that moment but I have tried now and it didn't work.

Environment:

```
Versions
	Tilix version: 1.6.5-0.0.2
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

Ubuntu 16.04.3
```

Profile:
```
{
    "child": {
        "child1": {
            "directory": "\/home\/test",
            "height": 497,
            "overrideCommand": "pwd",
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 479
        },
        "child2": {
            "directory": "\/home\/test",
            "height": 497,
            "profile": "2b7c4080-0ddd-46c5-8f23-563fd3ba789d",
            "readOnly": false,
            "synchronizedInput": true,
            "type": "Terminal",
            "width": 475
        },
        "orientation": 0,
        "position": 49,
        "ratio": 0.499479,
        "type": "Paned"
    },
    "height": 497,
    "name": "Default",
    "synchronizedInput": false,
    "type": "Session",
    "version": "1.0",
    "width": 959
}
```

Error on running `tilix -s ~/Desktop/test.json`:

```
The child process was aborted.
```

Thanks!

**Comment by gnunn1** [comment] 2017-09-28 13:58
pwd is going to run and just exist and you won't see the output because the infobar covers it. What happens if you change pwd to ```ls -l``` or something that prompts you?

**Comment by cazacugmihai** [comment] 2017-09-28 14:49
The same error is also thrown when using "ls -l".

(Profiles->Default->Command->"When command exists" is set to to "Hold the terminal open")

**Comment by gnunn1** [comment] 2017-09-28 15:06
OK, I'll have a look in more depth.

**Comment by cazacugmihai** [comment] 2017-09-28 15:16
Thank you! Tell me if I can help you with more info (logs maybe).

**Comment by cazacugmihai** [comment] 2017-09-28 18:21
Maybe it is not related but, with the latest version (from master), when executing something like:

```
vncviewer 192.168.100.1 &; exit
```

the error described in https://github.com/gnunn1/tilix/issues/1128#issuecomment-332860831 is thrown.

**Comment by gnunn1** [comment] 2017-10-02 22:21
It now returns the proper message of "Child exited normally with status 0" instead of the aborted message. I had a typo where I was testing the macro WEXITSTATUS instead of WIFEXITED.

**Closed** 2017-10-02 22:20 UTC

**Comment by cazacugmihai** [comment] 2017-10-11 21:38
I've tried the current [master](https://github.com/gnunn1/tilix) and the reported [issue](https://github.com/gnunn1/tilix/issues/1128#issuecomment-332860831) is still there.

```
tilix -v
Versions
	Tilix version: 1.7.0-0.0.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

Please make a test using the profile provided [here](https://github.com/gnunn1/tilix/issues/1128#issuecomment-332838264).

Maybe my assumption is wrong. Here is my expectation: when the user provides a command (e.g. `ls -lA`) in `Layout Options` -> `Session Load` -> `Command`, the command will be executed when the session is loaded and the user is allowed to use the terminal (the command line is available). I'm wrong?

Thanks!

**Comment by gnunn1** [comment] 2017-10-14 13:54
Yes, your assumption is incorrect. When you run a command it runs that instead of the shell. gnome-terminal and other terminal emulators, AFAIK, behave the exact same way.

**Comment by cazacugmihai** [comment] 2017-10-14 15:47
In this case, is there a way to enable somehow the behavior that I have described?

I have a session with lots of terminals and, on load, I would like that each terminal to execute a specific command (`child` -> `child1` -> `overrideCommand`) in the specified directory (`child` -> `child1` -> `directory`).

Thank you!

P.S. Should I create an issue (`feature`) for this?

**Comment by phw** [comment] 2017-10-14 15:57
You can just invoke the shell directly and pass the command to execute to it with the `-c` parameter, e.g.:

    /bin/bash -c ls

This will of course just run ls and exit afterwards. If you also want to use the shell after it exited, just invoke a shell command again after the first command, e.g.:

    /bin/bash -c "ls && /bin/bash"

**Comment by cazacugmihai** [comment] 2017-10-14 17:00
Yes, it works using your advise! Thank you very much!

**Comment by jpfleury** [comment] 2019-01-15 20:04
Is there a way to invoke the shell again after terminating the first command with "Ctrl+C"? For example, say we have a never ending command:

/bin/bash -c "while true; do date; sleep 10; done; /bin/bash"

At some point, we want to end it. With "Ctrl+C", the whole command is terminated and we have a message "The child process was aborted by signal 2."

How to have the shell back?

**Comment by gnunn1** [comment] 2019-01-15 20:33
Out of the box there is no support for that, you could try something similar to what is discussed here:

https://superuser.com/questions/198015/open-gnome-terminal-programmatically-and-execute-commands-after-bashrc-was-execu

**Comment by jpfleury** [comment] 2019-01-15 21:43
Thanks for your answer. I found a way. If I [catch](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html) Ctrl+C in my script, I can make it exit normally and have the shell back.

**Example:** set the command `/bin/bash -c "/path/to/script; /bin/bash"` in Tilix and use this script:

~~~
#!/bin/bash

trap "exit 0" SIGINT SIGTERM

while true; do
	date
	sleep 10
done
~~~
