### ISSUE TITLE
Doesn't always display lines after prompt when asking for input

### ISSUE THREAD

**Issue by bitstrings** [gnunn1/tilix#1007] opened 2017-07-10 19:04 UTC
Your prompt must be on the bottom of your terminal.

cd /usr
ls bin/{TAB}{TAB}

the "Display all 1235 possibilities? (y or n)" doesn't appear, instead we see another prompt.

If I remove scrollbar (profile) then it works.

**Comment by gnunn1** [comment] 2017-07-10 22:37
Duplicate of #998.

**Closed by gnunn1** 2017-07-10 22:37 UTC
