### ISSUE TITLE
Ctrl + Tab to switch between sessions

### ISSUE THREAD

**Issue by KSXGitHub** [gnunn1/tilix#1083] opened 2017-08-19 11:34 UTC
Just like <kbd>Alt + Tab</kbd>/<kbd>Super + Tab</kbd> to switch between application windows in desktop and <kbd>Ctrl + Tab</kbd> to switch between tabs in browser, Tilix should have a <kbd>Ctrl + Tab</kbd> for sessions. Right now, Tilix has <kbd>Ctrl + Alt + (N)</kbd> to switch to a specific `n`th session but no option to switch to next/prev session.

**Comment by bil-elmoussaoui** [comment] 2017-08-19 11:46
Duplicate of #890

**Comment by gnunn1** [comment] 2017-08-20 18:35
There are shortcuts available for Previous/Next Session, unfortunately gnome doesn't allow you to use Tab when assigning shortcuts so you need to do it in dconf. See the bug report @bil-elmoussaoui linked to for more information.

**Closed by gnunn1** 2017-08-20 18:35 UTC
Labels: duplicate

**Comment by phw** [comment] 2017-08-20 20:03
@gnunn1 Setting

    craShortcut.setProperty("accel-mode", GtkCellRendererAccelMode.OTHER)

in https://github.com/gnunn1/tilix/blob/master/source/gx/tilix/prefeditor/prefdialog.d#L727 would allow setting <Tab>. But I don't fully understand the difference to `GtkCellRendererAccelMode.GTK` and why some keyboard shortcuts are considered invalid GTK accelerators, so this might have some downsides?

**Comment by gnunn1** [comment] 2017-08-22 13:01
Thanks @phw, I'll have a look into this.
