### ISSUE TITLE
Bookmarks - Remote & Command missing <enter> in Wayland

### ISSUE THREAD

**Issue by arigit** [gnunn1/tilix#840] opened 2017-03-21 04:54 UTC
Fedora 25 / wayland
	Tilix version: 1.5.4
	VTE version: 0.46
	GTK Version: 3.22.10

When creating a Bookmark of type Remote or of type Command, e.g. create a Command with the following command: "ssh user@192.168.1.1" and then invoking the bookmark from within  from the bookmark menu from an active tile, all that happens is that the "command" string is pasted in the terminal, but without a carriage return so it doesn't get executed. In the example, selecting the new command I see:

ssh user@192.168.1.1

pasted in the terminal, and then for the ssh session to be executed I need to focus the terminal and type a carriage return. Same result when the bookmark is of Remote type.

Looks like either a bug (wayland?) or I am not understanding the way bookmarks are intended to be used.

**Comment by gnunn1** [comment] 2017-03-21 12:33
My thinking was to give the user the opportunity to edit the command before activating it so it doesn't feed the carriage return to the terminal after the bookmark. I'm open to changing it or making the behavior optional.

**Comment by phw** [comment] 2017-03-21 12:49
My suggestion would be to have this an option, similar how it is done in the password dialog. I would prefer that, as I actually often want to edit the command before executing it.

> ... I need to focus the terminal and type a carriage return

@arigit This part is interesting. Actually it is supposed to give the terminal the focus back after you selected a bookmark. I already reported this bug once, but closed it again since I could not reproduce it later. Is this maybe a Wayland bug (can't test on Wayland right now)?

**Comment by gnunn1** [comment] 2017-03-21 14:16
I've added an option to append a newline similar to Password dialog, thanks for the suggestion @phw.

I'll have a look at the focus issue before closing this.

**Comment by gnunn1** [comment] 2017-03-21 22:03
I wasn't able to reproduce the focus issue but I added a line to focus the terminal after the bookmark for good measure, hopefully that deals with it.

**Closed** 2017-03-21 22:03 UTC
Labels: enhancement

**Comment by arigit** [comment] 2017-03-22 04:27
Thanks for the fast response!

To see the focus quirk:

- open tilix, create a second terminal (add terminal down)
- focus moves to the second terminal automatically (this is normal)
- click on the terminal name of the first terminal to open the menu (popover), select Boomark, then double click on any bookmark
- the 'command' gets pasted on the first terminal but focus is still on the second terminal

**Comment by gnunn1** [comment] 2017-03-22 11:46
Have you tried the latest in master, the change I made yesterday to explicitly focus the terminal after selecting the bookmark has fixed this for me.

**Comment by sarlindo** [comment] 2017-08-19 15:01
I just downloaded installed the newest version to tilix, where do I find this option for the "enter" key to be sent automatically after selecting a bookmark? Can seem to find that option.

**Comment by sarlindo** [comment] 2017-08-19 16:10
@gnunn1 never mind, I now see the checkmark box below the bookmark window.
