### ISSUE TITLE
Click About from Gnome Shell menu crashes Tilix

### ISSUE THREAD

**Issue by vijaygopal1234** [gnunn1/tilix#1186] opened 2017-11-12 02:25 UTC
It causes a segmentation fault. There is no other debugging information when I run it from another terminal emulator.

**Comment by gnunn1** [comment] 2017-11-12 02:43
Is this a duplicate of #1157?

What version of Tilix are you using?

**Comment by vijaygopal1234** [comment] 2017-11-12 02:45
Yes, you can combine them! Sorry, I didn't find that.

**Comment by gnunn1** [comment] 2017-11-12 02:47
Close, duplicate.

**Closed by gnunn1** 2017-11-12 02:47 UTC
