### ISSUE TITLE
The function you are calling is not pressent in your version of GTK+.

### ISSUE THREAD

**Issue by Jim-Bar** [gnunn1/tilix#1464] opened 2018-07-09 12:26 UTC
Hello,

Tilix works no more after an update of my system:

```
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: 2018-07-09T14:19:07.440:application.d:loadResources:141 Could not load CSS /com/gexperts/Tilix/css/tilix.base320.css
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: object.Error@(0): The function you are calling is not pressent in your version of GTK+.
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ----------------
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? extern (C) void gtkd.Loader.Linker.unsupportedSymbol() [0x95e8f483]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? gdk.MonitorG.MonitorG gdk.Display.Display.getMonitor(int) [0x95e3ff00]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x610e09]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x61084b]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_closure_invoke [0x92b64fa4]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x92b76fc0]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit_valist [0x92b7fd5b]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit [0x92b8008e]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? gtk_widget_realize [0x8b59ed5b]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x8b5abc57]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_closure_invoke [0x92b64fa4]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x92b76afb]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit_valist [0x92b7fd5b]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit [0x92b8008e]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? gtk_widget_show [0x8b59b714]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x617384]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_closure_invoke [0x92b64fa4]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x92b76fc0]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit_valist [0x92b7fd5b]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit [0x92b8008e]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x616af6]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? extern (C) void gobject.DClosure.DClosure.d_closure_marshal!(int delegate(glib.c.types.Scoped!(gio.ApplicationCommandLine.ApplicationCommandLine).Scoped, gio.Application.Application)).d_closure_marshal(gobject.c.types.GClosure*, gobject.c.types.GValue*, uint, gobject.c.types.GValue*, void*, void*) [0x95cc8bec]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_closure_invoke [0x92b64fa4]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x92b76fc0]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit_valist [0x92b7f7f8]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_signal_emit [0x92b8008e]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x920efac2]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x920f1b1c]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? g_application_run [0x920f1ce1]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x61b79a]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x947ae69e]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x947ae5dd]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? _d_run_main [0x947ae4d8]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? __libc_start_main [0x9417382f]
Jul  9 14:19:07 AMA-LT-4547 gnome-session[1662]: ??:? [0x588ce8]
```

My version is:
```
$ tilix --version                                                                                                                                                                          14:19:08
Versions
	Tilix version: 1.8.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

I am on Ubuntu 16.04.4 LTS. For information I use the plugin Quake.

**Comment by gnunn1** [comment] 2018-07-09 12:45
Duplicate of #1457

**Closed by gnunn1** 2018-07-09 12:45 UTC
