### ISSUE TITLE
Long delay when changing the hostname

### ISSUE THREAD

**Issue by hamperfait** [gnunn1/tilix#1247] opened 2018-01-09 12:05 UTC
Whenever I change the hostname (either via the command `hostname NEWHOSTNAME` or editing the `/etc/hostname` file, whenever I open a new terminal it has a long delay until the terminal is operative.
The hostname has a structure [A-X]{2}[1-9]{5}[A-X] (ex. AB12345C).

If I change the hostname back to default it works again and terminal is operative from the start.
I have tried with different terminals and it happens only with Tilix.
Thanks a lot.

**Comment by gnunn1** [comment] 2018-01-09 13:27
Only thing I can think of that could be causing this is the trigger functionality, are you on Arch using the ```tilix-vte``` package by chance?

**Comment by hamperfait** [comment] 2018-01-09 14:10
No, I'm running Kali in a virtualbox environment...

**Comment by gnunn1** [comment] 2018-01-10 20:47
I just tried it and couldn't reproduce. Also, are you using the Automatic Profile Switching in Tilix?

What is the output of ```tilix --version```?

**Comment by hamperfait** [comment] 2018-01-11 07:49
Nope, I don't have it on.
Here's the output of `tilix --version`

`Versions
	Tilix version: 1.7.1
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
`

**Comment by gnunn1** [comment] 2018-06-23 16:49
I'm cleaning up issues and going to close this as just one of those things. If someone else has the issue and can provide steps to reproduce it let me know.

**Closed by gnunn1** 2018-06-23 16:49 UTC
Labels: Can't Reproduce, bug
