### ISSUE TITLE
Fully transparent terminal view

### ISSUE THREAD

**Issue by Salamandar** [gnunn1/tilix#1287] opened 2018-02-04 11:12 UTC
Since last update(s) (VTE ? Gtk ? GtkD ? LibPhobos ? Tilix ?), the terminal is fully transparent, independently from the "transparency" setting.

**Comment by gnunn1** [comment] 2018-02-04 14:10
Duplicate of #1257

**Closed by gnunn1** 2018-02-04 14:10 UTC

**Comment by Salamandar** [comment] 2018-02-04 14:21
Ok, Github did not want me to find closed issues.
