### ISSUE TITLE
Tilix creates an invisible window

### ISSUE THREAD

**Issue by NelsonBrandao** [gnunn1/tilix#1237] opened 2018-01-05 12:41 UTC
Hi,

Sometimes, can't really figure out what triggers this, tilix creates an invisible window with a few pixels in side on my desktop. This window sits over all content and can't be sent to the background, it also blocks the cursor from selecting anything below.

I know the window is from tilix because if I close all terminals it disappears.

I'm running Arch Linux with Gnome (latest version). Tilix was instead from [here](https://aur.archlinux.org/packages/tilix-bin) and I have the latest version.

`xprop` output when clicking on the invisible window:

```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_WINDOW_OPACITY(CARDINAL) = 8194797
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2800001
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DND
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 42883992, 42883993
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x28e5b97
WM_CLIENT_LEADER(WINDOW): window id # 0x2800001
_NET_WM_PID(CARDINAL) = 2022
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "machine"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 192 by 115
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_ICON_NAME(STRING) = "tilix"
_NET_WM_ICON_NAME(UTF8_STRING) = "tilix"
WM_NAME(STRING) = "tilix"
_NET_WM_NAME(UTF8_STRING) = "tilix"
```

**Comment by gnunn1** [comment] 2018-01-05 13:32
Any chance this is happening after a drag and drop of terminals, I'm just guessing based on this ```_NET_WM_WINDOW_TYPE_DND``` from your output. Tilix uses a Window for the drag image but it should be getting cleaned up after the drag completes, perhaps in your case it is not for some reason. If you can figure out how to reproduce it I would be happy to have a look.

**Comment by NelsonBrandao** [comment] 2018-01-09 09:19
I haven't been able to consistently reproduce it, but it doesn't seem to be related with dragging terminals since I rarely do this. I will keep trying.

**Comment by angystardust** [comment] 2018-01-16 17:43
Same thing here on a Fedora 27 with tilix-1.7.3-1.fc27.x86_64
It's a quite odd bug which render a quite invisible gray area-box in the center of the screen and makes the mouse-pointer completely (you can't click or select anything inside this area).
Unfortunately it also impact other applications (for ex. firefox, chrome) and the only thing you can do to restore the screen is to kill tilix.  I've just discovered that the cause of this issue was tilix-terminal as i tried to launch xkill and point to the gray box: tilix suddently was closed.
I still cannot reproduce the issue but it happens so many time during the day that i'm thinking of switching to another terminal 'till this bug is fixed :(

**Comment by NelsonBrandao** [comment] 2018-03-12 16:29
Just had this happen when dragging a split and "_alt-tabbing_" at the same time. The preview next to the mouse became stuck.

Check the screenshot below

![screenshot from 2018-03-12 16-26-50](https://user-images.githubusercontent.com/1036806/37296244-3f08bb62-2612-11e8-995a-484f2cc075ed.png)

**Comment by gnunn1** [comment] 2018-03-12 16:37
I'm not sure what the screenshot is showing, what am I missing?

I just tried dragging and alt-tabbing at the same time and it worked fine for me unfortunately. Are you able to reproduce it consistently using that technique?

**Comment by NelsonBrandao** [comment] 2018-03-12 17:02
@gnunn1 There is a black overlay box on the screenshot, its almost transparent but you should be able to see it. Added a red line around it.

![screenshot from 2018-03-12 16-26-50](https://user-images.githubusercontent.com/1036806/37297925-df42de60-2616-11e8-88df-9a6c8e450034.png)

I'm able to get it 100% of the times but I was able to reproduce it at least another time. The first time was by mistake, I was just trying to alt-tab but touch the touchpad.

**Comment by gnunn1** [comment] 2018-03-12 17:12
Thanks, I see it now. Is it reproduceable?

**Comment by gnunn1** [comment] 2018-06-23 16:51
Thanks for the bug report however given I cannot reproduce it I'm not planning on spending any time investigating it further at this point. As a result I am closing the issue has part of cleaning up older issues, feel free to re-open if you disagree and we can discuss.

**Closed by gnunn1** 2018-06-23 16:51 UTC
Labels: Can't Reproduce, bug

**Comment by jturcotte** [comment] 2018-10-26 11:40
I've switched to Tilix maybe 6 months ago and I've seen the issue maybe 3-4 times only, so it's not easy to catch.

This time however the window isn't gray, I can see the content. I don't know how it appears in my case, but I went to lunch and locked gnome shell, and when unlocking it this window was right there. Here is a screenshot, maybe the content can help:

![image](https://user-images.githubusercontent.com/839935/47564029-eee70380-d923-11e8-9860-837951989101.png)

It looks like the session sidebar screenshot, but isn't the same width, and only includes the top split:

![image](https://user-images.githubusercontent.com/839935/47564199-7765a400-d924-11e8-8460-b5eafa51a59e.png)

Here is the xwininfo, maybe it's useful:
```
xwininfo: Window id: 0x1d17180 "tilix"

  Absolute upper-left X:  615
  Absolute upper-left Y:  251
  Relative upper-left X:  615
  Relative upper-left Y:  251
  Width: 512
  Height: 136
  Depth: 32
  Visual: 0x555
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x1c00006 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: yes
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +615+251  -2633+251  -2633-1533  +615-1533
  -geometry 512x136+615+251
```

**Comment by jturcotte** [comment] 2018-10-26 12:00
OK I managed to reproduce it by repeatedly dragging the titlebar of a terminal and drop it on itself. The drag preview window sticks there one time out of 20 maybe. I'm not quite sure what triggers it but in this case it looks like it could be caused by dropping it while the window is already in-flight because of a previous drag.

![image](https://user-images.githubusercontent.com/839935/47564880-d2989600-d926-11e8-812c-ca9e1c8d513b.png)

**Comment by gnunn1** [comment] 2018-10-27 22:43
I'm not able to reproduce it myself, but I've added some code based on a hunch to try to help with this. Thanks for the report, appreciate it.

**Comment by xurizaemon** [comment] 2019-01-20 22:45
Observing this with Tilix 1.7.7-1ubuntu2, adding notes in case it's helpful. Keyword: :ghost: ghost window :)

The rectangle is near invisible except at some angles (see attached photos front on then at angle; rectangle is inside the "Add comment" box). Unable to interact with the (supposedly) frontmost app behind this window when ghost window is present.

Confirmed that it's Tilix via `xwininfo`. Thought it was gnome-screenshot for ages!

**Comment by gnunn1** [comment] 2019-01-20 23:00
This has been fixed in later versions, please upgrade.

**Comment by Glandos** [comment] 2019-03-07 13:59
I'm using Debian/testing, with Xfce, and Tilix 1.8.9.
Unfortunately, this is not fixed. I'm having this once in a while, especially after Tilix is launched for a long time (>4days).
Is there any other solution than closing all Tilix windows? Is it possible to disable those small preview windows when drag'n'dropping?

**Comment by jturcotte** [comment] 2019-03-07 14:39
@Glandos Do you have reasons to believe that this is also related to drag'n drop?

Not sure if this is relevant information, but I haven't seen the issue once since the fix in October. I'm using Tilix also over many days, currently at version 1.8.9 but in Gnome Shell. So I'm wondering if it's somehow triggered by something else in your case.

**Comment by Glandos** [comment] 2019-03-07 15:09
![capture d ecran_2019-03-07_16-06-47](https://user-images.githubusercontent.com/297578/53966236-13819200-40f3-11e9-81d9-fbe70b4633a3.png)

And running `xprop` on it:
```
> xprop
_NET_WM_WINDOW_OPACITY(CARDINAL) = 72516227
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x4200001
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DND
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 69822425, 69822426
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x42967d8
WM_CLIENT_LEADER(WINDOW): window id # 0x4200001
_NET_WM_PID(CARDINAL) = 24551
WM_LOCALE_NAME(STRING) = "fr_FR.UTF-8"
WM_CLIENT_MACHINE(STRING) = "poulpe"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 383 by 201
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_ICON_NAME(STRING) = "tilix"
_NET_WM_ICON_NAME(UTF8_STRING) = "tilix"
WM_NAME(STRING) = "tilix"
_NET_WM_NAME(UTF8_STRING) = "tilix"
```
The window just happened today.

Just another idea: I don't really use drag'n'drop, but I often use double-click on terminal title to maximize/minimize a terminal.

**Comment by vkaracic** [comment] 2019-07-10 11:59
@Glandos FWIW  I updated to 1.9.1 and the shadow window stopped appearing.

**Comment by ashraffouda** [comment] 2019-07-30 09:29
it still happening after upgrading to 1.9.1
![Screenshot from 2019-07-30 11-26-38](https://user-images.githubusercontent.com/1689456/62117862-08571a80-b2bd-11e9-8cbd-e849af9f314e.png)
![Screenshot from 2019-07-30 11-27-47](https://user-images.githubusercontent.com/1689456/62117974-2b81ca00-b2bd-11e9-98d2-22c320062d46.png)

**Comment by angystardust** [comment] 2019-07-30 15:36
@ashraffouda sadly that's why I stopped using Tilix for Terminator

**Comment by vkaracic** [comment] 2019-09-10 12:43
Confirming that it still happens to me too, but on 1.9.1 it is every 2 or 3rd time I reposition a window.

**Comment by Glandos** [comment] 2019-09-11 14:04
@gnunn1 Would you be interested in a core dump?

**Comment by gnunn1** [comment] 2019-09-11 15:05
No, I'm not actively maintaining Tilix anymore except for things that affect me personally, see #1700

Having said that I suspect the issue is something is broken with GtkD or the D GC as I'm seeing objects not being GC'ed properly anymore (VTE for example). It's something I'll look at but don't have a timeline as my priorities are elsewhere and it's not affected me using Tilix.

**Comment by PD-Extron** [comment] 2019-10-30 19:59
I have a workaround for those who do not want to restart Tilix just to get rid of that "ghost" window, which prevents you from interacting with other windows that occupy the same coordinates. 

Install xdotool (I use Ubuntu).
$ sudo apt-get install xdotool 

Get the window ID assuming you can see it!  Just click on any point in the window.
$ xwininfo

Resize the window down to practically nothing 
$ xdotool windowsize <window id> 2 2

Move the window anywhere (I moved all the way to the right at current y location)
$ xdotool windowmove <window id> 1920 y

That should do it.  Hope this helps.

**Comment by teeberg** [comment] 2020-10-13 18:25
And here the same thing as a tiny bash script that you can wrap up as `hide_window.sh`:
```bash
#!/bin/bash
windowId="$(xwininfo | awk '{ if ($2 == "Window" && $3 == "id:") { print $4 } }')"
xdotool windowsize "$windowId" 2 2
xdotool windowmove "$windowId" 1920 y
```
