### ISSUE TITLE
error during compiling tilix 

### ISSUE THREAD

**Issue by dacorsa** [gnunn1/tilix#2152] opened 2023-02-22 10:15 UTC
HI
i always compile tilix successfully on my ubuntu 22.04, but now i have an error:

make: ***  Nessuna regola per generare l'obiettivo «clean».  Arresto.
    Starting Performing "release" build using /usr/bin/dmd for x86_64.
  Up-to-date gtk-d:gtkd 3.9.0: target for configuration [library] is up to date.
  Up-to-date gtk-d:vte 3.9.0: target for configuration [library] is up to date.
    Building tilix ~master: building configuration [default]
source/gx/tilix/prefeditor/prefdialog.d(960,16): Error: unable to read module `xml`
source/gx/tilix/prefeditor/prefdialog.d(960,16):        Expected 'std/xml.d' or 'std/xml/package.d' in one of the following import paths:
import path[0] = source/
import path[1] = /root/.dub/packages/gtk-d-3.9.0/gtk-d/generated/gtkd
import path[2] = /root/.dub/packages/gtk-d-3.9.0/gtk-d/generated/vte
import path[3] = /usr/include/dmd/phobos
import path[4] = /usr/include/dmd/druntime/import

Can you help me?

best regards

**Comment by dacorsa** [comment] 2023-03-05 10:21
someone can help me?

i have installed this, but same error occurs:

sudo apt install r-cran-xml r-cran-base64enc r-cran-digest r-cran-readmzxmldata 

Best regards

**Comment by dacorsa** [comment] 2023-03-05 10:39
maybe the version r-cran-xml è già alla versione più recente (3.99-0.10-1) is not good?

std/math/hardware.d(336,2): Error: undefined identifier `optStrategy`
std/math/hardware.d(428,2): Error: undefined identifier `optStrategy`
std/math/hardware.d(451,2): Error: undefined identifier `optStrategy`
std/math/hardware.d(1101,2): Error: undefined identifier `optStrategy`

someone can help me?

best regards

**Comment by cifvts** [comment] 2023-04-19 14:07
I think the problem is that `std/xml.d` has been deprecated[1] and recently removed[2]. Either the code need to use the module from the https://github.com/dlang/undeaD repository or need to use a different library. They suggested [dxml](https://code.dlang.org/packages/dxml) but has not been updated recently, while [serialized](https://code.dlang.org/packages/serialized) seems to be active.

[1] https://dlang.org/changelog/2.092.0.html#deprecate-xml
[2] https://dlang.org/changelog/2.101.0.html#remove-std-xml

**Comment by ximion** [comment] 2023-04-20 00:36
Fixed in master.

**Closed by ximion** 2023-04-20 00:36 UTC
