### ISSUE TITLE
Support for secondary hotkeys

### ISSUE THREAD

**Issue by ervoiox** [gnunn1/tilix#1384] opened 2018-04-22 04:15 UTC
Hi,

I use a ThinkPad where it has `Backward` and `Forward` keys, which are sent as `XF86Forward` and `XF86Back` key events. I use tabs with tilix and its great for moving between tabs when I am using the laptop keyboard. But when I switch to a external keyboard, it obviously does not have these `Backward` or `Forward` keys. It would be nice if tilix had support for setting a secondary set of hot keys or handled these types of special keys, ie `XF86Forward` would be treated at `Alt+Right` and `XF86Back` as `Alt+Left`.

**Comment by gnunn1** [comment] 2018-04-22 13:47
Duplicate of #631

**Closed by gnunn1** 2018-04-22 13:47 UTC
