### ISSUE TITLE
Doesn't display lines after prompt when asking for input

### ISSUE THREAD

**Issue by c1rcu17** [gnunn1/tilix#998] opened 2017-07-03 12:59 UTC
I have this problem, and I don't know if it's a bug or not. When there is some text on the terminal (sufficient to make the scrollbar appear), I cannot see the lines that appear after the prompt for a tab completion.

To reproduce:
Open a terminal -> type some commands to make the scrollbar appear -> type "sudo apt-get install " -> hit <kbd>Tab</kbd>..
There should be a question like this: "Display all 57506 possibilities? (y or n)" but that line quickly gets replaced by another prompt.
I can confirm that the terminal still is waiting for a y or n.

I'm using Xbuntu 17.04
```shell
$ tilix --version
Versions
	Tilix version: 1.6.1
	VTE version: 0.44
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment] 2017-07-03 13:27
I'm not able to duplicate this. Can you try the following which is what I'm doing:
```
cd /usr/bin
ls -l
ls p<tab>
```
I then see ```Display all 269 possibilities? (y or n)``` just fine.

Also, are you using powerline or anything unusual in your prompt?

**Comment by gnunn1** [comment] 2017-07-03 13:28
Also, do you get the same behavior in gnome-terminal?

**Comment by c1rcu17** [comment] 2017-07-03 14:06
Hello, thank you for your quick answer.

I tried with your commands and it behaves the same. I'm not using powerline. The shell is bash and the only customization I have in my .bashrc is this:

```shell
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
  source /etc/profile.d/vte-2.91.sh
fi
```

Also, I installed gnome-terminal, and I don't get the same behavior. I get the expected one. And the same is true about xterm.
I attached a video.
[bug.ogv.zip](https://github.com/gnunn1/tilix/files/1119749/bug.ogv.zip)

**Comment by gnunn1** [comment] 2017-07-03 14:42
Thanks, unfortunately I have no idea what the issue could be. @f2404 Do you get the same issue in XFCE?

**Comment by f2404** [comment] 2017-07-03 14:45
@gnunn1 I will have to check it tonight, when I get home.

**Comment by f2404** [comment] 2017-07-03 22:12
No, I cannot reproduce it on my home machine either.

**Comment by gnunn1** [comment] 2017-07-03 23:03
Thanks @f2404.

@c1rcu17 can you try commenting out that bit in .bashrc and see if it makes any difference, because you source it depending on the ```$TILIX_ID``` gnome-terminal doesn't use it. This is just to see if that's the problem.

If this doesn't fix it, I'm not sure what else to suggest. Unfortunately, I don't support XFCE (just Unity and Gnome), so I'll likely close this as a Won't Fix.

**Comment by c1rcu17** [comment] 2017-07-04 08:33
@gnunn1, I tried that but it did not fix. This is really something XFCE related, because I tried (at home) booting from two live CDs (xubuntu 17.04 and ubuntu-gnome 17.04), just installing tilix, nothing more, and xubuntu has this bug while ubuntu-gnome does not. I will let you know if I find some explanation for this behavior. Thank you

**Comment by gnunn1** [comment] 2017-07-04 12:16
Thanks for the update @c1rcu17, if you find the problem please feel free to re-open this issue.

**Comment by bitstrings** [comment] 2017-07-09 04:00
I have the same problem.

Easy to reproduce.

Your prompt must be on the bottom of your terminal.

cd /usr
ls bin/<tab><tab>

the "Display all 1235 possibilities? (y or n)" doesn't appear, instead we see another prompt.

**Comment by gnunn1** [comment] 2017-07-10 22:37
@bitstrings It works fine for me with the prompt at the bottom of the terminal. Having said that, I wonder if it's related to the overlay scrollbar and the version of VTE and GTK. Can you post the output of ```tilix --version```.

Right now it uses the overlay scrollbar whenever it detects GTK 3.22, however I wonder if an older version of VTE with a newer version of GTK is problematic. Here's my output on Arch:

```
Versions
	Tilix version: 1.6.2-0.0.1
	VTE version: 0.48
	GTK Version: 3.22.16

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=1
	Badges enabled=1
```
Cheers,

Gerald

**Comment by bitstrings** [comment] 2017-07-10 22:42
<pre>
Versions
	Tilix version: 1.6.1
	VTE version: 0.48
	GTK Version: 3.22.16

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
</pre>

**Comment by gnunn1** [comment] 2017-07-10 22:48
Well there goes that theory, a few more questions:

a. what desktop environment are you using, Gnome? 
b. Are you using the Adwaita theme or something else?
c. Are you using powerline or anything else funky in the prompt?

**Comment by bitstrings** [comment] 2017-07-10 22:51
a. Happens on my laptop with gnome 3.24, also Mate 1.18 on my desktop
b. I am using Adapta (i will test Adwaita)
c. Nope

**Comment by bitstrings** [comment] 2017-07-10 22:55
Tested with Adwaita, still no go.

**Comment by gnunn1** [comment] 2017-07-10 23:11
I'm not sure what the issue is off-hand, I'll have to give it some thought. It could still be related to the fact I'm using an overlay scrollbar unlike gnome-terminal. When the prompt is supposed to appear after the second tab, can you manually try scrolling the bar down by grabbing it with the mouse to see if it shows up?

Also, is scroll on output configured in your profile?

**Comment by gnunn1** [comment] 2017-07-10 23:11
Oh and I assume there is no issue with gnome-terminal or xterm?

**Comment by bitstrings** [comment] 2017-07-10 23:13
There are no issue with gnome-terminal, xterm and mate-terminal.

This is what happens.

![image](https://user-images.githubusercontent.com/911165/28044190-e5bae884-65a3-11e7-9999-7206098be58b.png)

**Comment by gnunn1** [comment] 2017-07-10 23:16
Wait is your prompt multiline? Can you post your PS1 configuration for it and I'll try using it to duplicate it.

**Comment by bitstrings** [comment] 2017-07-10 23:17
Yeah I was editing my post. Look.

![image](https://user-images.githubusercontent.com/911165/28044265-5f46dbfe-65a4-11e7-8449-c629cffb7bf8.png)

**Comment by gnunn1** [comment] 2017-07-10 23:20
I'd still like to try whatever you are using for PS1, mine is bog standard:

```
PS1='[\u@\h \W]\$ '
```

**Comment by bitstrings** [comment] 2017-07-10 23:37
[bash.bashrc.local.zip](https://github.com/gnunn1/tilix/files/1137340/bash.bashrc.local.zip)

**Comment by gnunn1** [comment] 2017-07-10 23:44
No issues for me with your bashrc file so that's not it.

**Comment by f2404** [comment] 2017-07-11 00:00
I found that a similar effect could be reached by resizing the window, i.e.
1. type `ls -l /usr/bin/`
2. press Tab - `Display all? (y/n)` prompt appears
3. resize the window
4. prompt disappears, `ls -l /usr/bin/` is shown instead

**Comment by gnunn1** [comment] 2017-07-11 00:05
@f2404 Interesting, I wonder if it's a VTE bug of some sort since gnome-terminal behaves identically to tilix in that instance.

**Comment by f2404** [comment] 2017-07-11 00:08
@gnunn1 Yep, I've also checked it on xfce4-terminal - and its behavior is similar as well. Must be vte-related.

Can it be that the people who are seeing the issue are getting their terminal window resized somehow? by the WM?

**Comment by f2404** [comment] 2017-07-11 00:09
@gnunn1 Actually, xterm behaves similarly as well, so it's not vte only.

**Comment by gnunn1** [comment] 2017-07-11 00:14
@f2404 Thanks but I'm thinking you are on the right track. It could be the overlay scrollbar exacerbating the issue as AFAIK Tilix is the only VTE terminal emulator to use it at the moment, everybody else is using a separate scrollbar widget. I'm wodnering this since @bitstrings notes he doesn't get the issue with the scrollbar disabled.

I could build a test version from 1.6.1 that forces a separate scrollbar, @bitstrings would you be willing to test this out?

**Comment by bitstrings** [comment] 2017-07-11 00:25
Of course.

**Comment by gnunn1** [comment] 2017-07-11 00:39
You can download the test version here, it's just the binary so you all you need to do is unzip and run it with ```.\tilix```. You should see a normal scrollbar instead of the overlay scrollbar.

http://gexperts.com/files/tilix.zip

**Comment by bitstrings** [comment] 2017-07-11 00:42
Well it looks like it works!

**Comment by gnunn1** [comment] 2017-07-11 01:10
Ok so it's the overlay scrollback, I'll enhance the scroll option to have three options: no scrollbar, normal and overlay.

**Comment by gnunn1** [comment] 2017-07-11 11:48
One drawback with this option is that it's going to require a re-start of tilix since it applies when terminal widgets are created.

**Comment by phw** [comment] 2017-07-11 13:06
I also tried to reproduce this. I cannot reproduce the general behavior at all on Arch with Gnome. When using bash the question disappears on terminal resize, as @f2404 explained above. With zsh that is also not reproducible.

My guess is that the question disappearing on terminal resize is normal behavior for bash, but somehow the overlay scrollbar triggers a resize of the terminal on some environments.

**Closed** 2017-07-12 23:49 UTC
Labels: bug, Can't Reproduce
