### ISSUE TITLE
Issue with bold fonts with Terminus font

### ISSUE THREAD

**Issue by ryanrms** [gnunn1/tilix#1328] opened 2018-03-11 22:00 UTC
Steps to reproduce:

Install Tilix (great terminal emulator btw)
Install package xfonts-terminus (ubuntu package name)
Set Tilix profile to use Terminus using custom font option

Expected behavior:  Regular fonts are in regular width, bold fonts are bolded
Actual behavior:  Bold fonts display as regular width fonts in programs such as ncmpcpp

Workaround:
Set Tilix profile to use Terminus Bold as the font
Expected Behavior:  All fonts bold
Actual Behavior:  All fonts regular, except bold which display properly as bold

Note that this issue isn't observed when using other fonts like Ubuntu Mono, perhaps it is due to Terminus being a pixel font rather than a regular font.

**Comment by gnunn1** [comment] 2018-03-11 22:02
Do you see the same issue in gnome-terminal? Tilix uses the same terminal emulator so just wondering if the issue is with that or something specific to tilix.

**Comment by egmontkob** [comment] 2018-03-11 23:02
> Expected behavior: Regular fonts are in regular width, bold fonts are bolded
> Actual behavior: Bold fonts display as regular width fonts in programs such as ncmpcpp

I can reproduce this up to size 9, but no longer at size 10 or larger (both tilix and g-t). I guess this is simply an issue with the font: the bold counterpart is actually not any bolder at small sizes.

> Workaround: [...]
> Actual Behavior: All fonts regular, except bold which display properly as bold

Here VTE's "faux bold" kicks in (which we're [planning to remove](https://bugzilla.gnome.org/show_bug.cgi?id=756010)): it shifts the letters by 1px and prints them again over the original ones to achieve bold effect. It does so because it cannot locate any installed font that claims to be the bold counterpart of the chosen one, since the chosen one already claims to be bold.

**Comment by gnunn1** [comment] 2018-03-12 13:38
Thanks @egmontkob, this is something that is in VTE's purview and not tilix so I'm going to close this.

**Closed by gnunn1** 2018-03-12 13:38 UTC
