### ISSUE TITLE
Tilix and tmux over ssh

### ISSUE THREAD

**Issue by itoshkov** [gnunn1/tilix#911] opened 2017-05-05 08:21 UTC
Here is an idea I have had for some time. I'd love to see it implemented but it may be a bit far fetched.

A common use-case among programmers and sysadmins is to ssh to a remote server and run tmux or screen on it. Both of these provide windows and panes, which are purely text-based. I think it would be very useful if there is a way to "map" these to real tabs and panes in tilix.

One way this could be handled is to require the presence of special tmux plugin, which could provide information about the current layout and handle commands for managing panes and windows. I'm not sure how it will be able to communicate with tilix (and it's a good idea to make this communication in such manner that it doesn't break things for other terminals).

I know this is a big project and it may be outside of the scope of tilix. But I think it could be a very good feature to have.

P.S. I googled a bit but I couldn't find plugins or other extensions mechanism for GNU Screen.

**Comment by gnunn1** [comment] 2017-05-05 09:03
I think this is a duplicate of #480.

**Closed by gnunn1** 2017-05-05 09:03 UTC
Labels: duplicate
