### ISSUE TITLE
Add terminal down (Ctrl-Alt-d) closes terminal split when maximised

### ISSUE THREAD

**Issue by wezm** [gnunn1/tilix#1184] opened 2017-11-10 20:30 UTC
I have seen there are a number of other closed issues related to the add split shortcuts so I'll understand if this fits into the same category (won't fix, works as intended). I figured it was worth raising anyway as this is a edge case in the UI that bites me now and then. Also I'm aware I could change the shortcut but I'm used to the default at this point and would prefer to not have to change it everywhere I use Tilix if possible.

Steps to reproduce:

- Add a few horizontal splits (add terminal down)
- Maximise one of the splits
- _Time passes._ Forget the split is maximised and type Ctrl-Alt-d to add a new one
- Be surprised when terminal closes instead of adding a new split

It appears that when maximised Tilix doesn't intercept the shortcut so it goes to the terminal, which sees Ctrl-d and closes.

Expected behaviour (some ideas):

- Nothing happens
- There is some visual reminder that the terminal is maximised
- The current terminal is restored and the new split added

**Comment by gnunn1** [comment] 2017-11-10 21:03
Honestly the default shortcut choice is poor, when I selected it I wasn't aware of ctrl-alt-d closing the terminal. Tilix should either eat the shortcut everywhere or change it to a better default.

**Comment by gnunn1** [comment] 2017-12-21 21:27
Actually I'm looking at this again, isn't ctrl-shift-d the shortcut that closes the terminal? ctrl-alt-d works fine for me, when I maximize the terminal and hit that shortcut I see the bell go off but that's it, the terminal doesn't actually close.

**Comment by arcticicestudio** [comment] 2017-12-22 04:49
For me the terminal closes when pressing <kbd>Ctrl</kbd>+<kbd>d</kbd>

**Comment by wezm** [comment] 2017-12-22 04:57
It appears to be shell specific. I use `zsh` and the issue presents itself when using it (I.e. the terminal closes if I type <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>d</kbd> into a maximized pane). If I run bash instead the terminal does not close.

**Comment by gnunn1** [comment] 2017-12-22 15:05
The issue is that the tiling actions are disabled when the terminal is maximized which is why the buttons in the headerbar are disabled. Unfortunately GTK doesn't swallow the shortcut for disabled actions which is why it goes through to the terminal. I'm not sure if there is a good solution for this, I'll have to look into it further.

**Comment by wezm** [comment] 2017-12-22 20:08
Since it's shell specific it wouldn't be unreasonable to close this issue. Now that I know it's zsh I might be able to find a way to prevent it from exiting on that shortcut.

**Comment by gnunn1** [comment] 2017-12-29 23:34
Thanks @wezm, I'm also not seeing any easy way to handle this in tilix that wouldn't have to cover various edge cases and be complicated. I'm closing the issue, it can be re-opened if someone has a new proposal.

**Closed by gnunn1** 2017-12-29 23:34 UTC
Labels: bug
