### ISSUE TITLE
Terminals going gray

### ISSUE THREAD

**Issue by diogocalgaro** [gnunn1/tilix#1228] opened 2017-12-21 09:52 UTC
After some hours left alone (from one day to another, for example), some terminals goes gray and I cannot use then again. Just hitting some ctrl-c / ctrl-d to close then.

It started in 1.7.3, and I'm using Fedora 27 with Plasma 5.

Here is a screenshot example:
![screenshot_20171221_074912](https://user-images.githubusercontent.com/8246699/34250394-dcd192d0-e623-11e7-88f9-ff9b0942947c.png)

In the picture it has 4 terminals, but only one usable.

**Comment by gnunn1** [comment] 2017-12-21 13:46
I suspect what is happening is the terminals are closing for some reason but not raising the expected signal to tilix to close the split. If you open the sidebar, does it render a preview with the gray terminals or are the missing terminals shown there?

Note that I do not support Plasma, just Unity and Gnome. I will however try to leave a terminal emulator open for awhile and see if I can reproduce this on Gnome. If any other users are having this issue I'd appreciate hearing about it.

On your end, can you try running tilix from konsole and reproduce this issue. When it happens is there any logging shown in konsole from tilix that might give me a clue as to the issue?

**Comment by diogocalgaro** [comment] 2017-12-21 15:15
I closed this page with the errors, but I will do as you suggested, to collect more info. Thanks.

**Comment by gileshuang** [comment] 2017-12-23 08:50
Has the same issue here, with ArchLinux, gnome-shell 3.26.2. Installing tilix from aur/tilix-bin.
After going gray, if I do something to TIlix, such as create new session or close some session, some of grayed terminal chould go back. But sometimes, after some terminal going gray, all of Tilix session crash randomly.
I am using Tilix in my production workstation. crashed terminal always bring my work into trouble.
Sorry for lacking debug logs. If I got some logs, I will put them there.

**Comment by gileshuang** [comment] 2017-12-23 09:14
I found something like that in systemd journal:

```
12月 23 15:04:15 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:22 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:22 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:22 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:23 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:23 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:23 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:24 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:24 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:24 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_scale_factor: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed
12月 23 15:04:26 ITA-1401-0045.synacast.local tilix[10859]: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed
```

And a coredump there:

```
12月 23 16:24:51 ITA-1401-0045.synacast.local systemd-coredump[21354]: Process 10859 (tilix) of user 1000 dumped core.
                                                                        
                                                                        Stack trace of thread 10859:
                                                                        #0  0x00007f3a8282d860 raise (libc.so.6)
                                                                        #1  0x00007f3a8282eec9 abort (libc.so.6)
                                                                        #2  0x00007f3a81184c06 g_assertion_message (libglib-2.0.so.0)
                                                                        #3  0x00007f3a81184fcc g_assertion_message_expr (libglib-2.0.so.0)
                                                                        #4  0x00007f3a7f7e8d05 gtk_widget_unregister_window (libgtk-3.so.0)
                                                                        #5  0x00007f3a7f7e8e2c n/a (libgtk-3.so.0)
                                                                        #6  0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #7  0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #8  0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #9  0x00007f3a7f6c2501 n/a (libgtk-3.so.0)
                                                                        #10 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #11 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #12 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #13 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #14 0x00007f3a7f56f1dc n/a (libgtk-3.so.0)
                                                                        #15 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #16 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #17 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #18 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #19 0x00007f3a7f56f1dc n/a (libgtk-3.so.0)
                                                                        #20 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #21 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #22 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #23 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #24 0x00007f3a7f56f1dc n/a (libgtk-3.so.0)
                                                                        #25 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #26 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #27 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #28 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #29 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #30 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #31 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #32 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #33 0x00007f3a7f56f1dc n/a (libgtk-3.so.0)
                                                                        #34 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #35 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #36 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #37 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #38 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #39 0x00007f3a814772c2 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #40 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #41 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #42 0x00007f3a7f56f1dc n/a (libgtk-3.so.0)
                                                                        #43 0x00007f3a7f7e8dd8 n/a (libgtk-3.so.0)
                                                                        #44 0x00007f3a81477c01 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #45 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #46 0x00007f3a7f7e45a5 gtk_widget_unrealize (libgtk-3.so.0)
                                                                        #47 0x00007f3a7f7f030e gtk_widget_unparent (libgtk-3.so.0)
                                                                        #48 0x00007f3a7f56f29c n/a (libgtk-3.so.0)
                                                                        #49 0x00007f3a8145de0a g_cclosure_marshal_VOID__OBJECTv (libgobject-2.0.so.0)
                                                                        #50 0x00007f3a81477c01 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #51 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #52 0x00007f3a7f5ba891 gtk_container_remove (libgtk-3.so.0)
                                                                        #53 0x000055f9fe4644c7 n/a (tilix)
                                                                        #54 0x000055f9fe1802be n/a (tilix)
                                                                        #55 0x000055f9fe17ee41 n/a (tilix)
                                                                        #56 0x000055f9fe17e3bd n/a (tilix)
                                                                        #57 0x000055f9fe17e17f n/a (tilix)
                                                                        #58 0x000055f9fe20d872 n/a (tilix)
                                                                        #59 0x000055f9fe3dcded n/a (tilix)
                                                                        #60 0x00007f3a8145f6f5 g_closure_invoke (libgobject-2.0.so.0)
                                                                        #61 0x00007f3a814730b0 n/a (libgobject-2.0.so.0)
                                                                        #62 0x00007f3a81477696 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #63 0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        
                                                                        Stack trace of thread 10862:
                                                                        #0  0x00007f3a828e4f2b __poll (libc.so.6)
                                                                        #1  0x00007f3a81190ed3 n/a (libglib-2.0.so.0)
                                                                        #2  0x00007f3a81190fae g_main_context_iteration (libglib-2.0.so.0)
                                                                        #3  0x00007f3a81191002 n/a (libglib-2.0.so.0)
                                                                        #4  0x00007f3a811851eb n/a (libglib-2.0.so.0)
                                                                        #5  0x00007f3a8311b08a start_thread (libpthread.so.0)
                                                                        #6  0x00007f3a828ef42f __clone (libc.so.6)
                                                                        
                                                                        Stack trace of thread 10863:
                                                                        #0  0x00007f3a828e9e29 syscall (libc.so.6)
                                                                        #1  0x00007f3a811b85dd n/a (libglib-2.0.so.0)
                                                                        #2  0x00007f3a81476b66 g_signal_emit_valist (libgobject-2.0.so.0)
                                                                        #3  0x00007f3a81478920 g_signal_emit (libgobject-2.0.so.0)
                                                                        #4  0x00007f3a81465bf6 n/a (libgobject-2.0.so.0)
                                                                        #5  0x00007f3a8146152a g_object_notify (libgobject-2.0.so.0)
                                                                        #6  0x00007f3a8179b5d1 n/a (libgio-2.0.so.0)
                                                                        #7  0x00007f3a8179b5e9 n/a (libgio-2.0.so.0)
                                                                        #8  0x00007f3a8118f0be g_main_context_dispatch (libglib-2.0.so.0)
                                                                        #9  0x00007f3a81190f69 n/a (libglib-2.0.so.0)
                                                                        #10 0x00007f3a81191f42 g_main_loop_run (libglib-2.0.so.0)
                                                                        #11 0x00007f3a816fc208 n/a (libgio-2.0.so.0)
                                                                        #12 0x00007f3a811851eb n/a (libglib-2.0.so.0)
                                                                        #13 0x00007f3a8311b08a start_thread (libpthread.so.0)
                                                                        #14 0x00007f3a828ef42f __clone (libc.so.6)
                                                                        
                                                                        Stack trace of thread 10864:
                                                                        #0  0x00007f3a828e4f2b __poll (libc.so.6)
                                                                        #1  0x00007f3a81190ed3 n/a (libglib-2.0.so.0)
                                                                        #2  0x00007f3a81190fae g_main_context_iteration (libglib-2.0.so.0)
                                                                        #3  0x00007f3a7534db0e n/a (libdconfsettings.so)
                                                                        #4  0x00007f3a811851eb n/a (libglib-2.0.so.0)
                                                                        #5  0x00007f3a8311b08a start_thread (libpthread.so.0)
                                                                        #6  0x00007f3a828ef42f __clone (libc.so.6)

```

**Comment by diogocalgaro** [comment] 2017-12-23 13:08
I noticed this behaviour too: in my first screenshot, 3 terminals are gray and 1 is ok. When I close this one ok, one of the others becomes responsive again, and so on. In my case, it usually happens in only one page. The others stay fine.
When I return to work from holidays it should be gray and I will post the logs.

**Comment by diogocalgaro** [comment] 2017-12-26 12:50
It did not happened again these days, but I am running it from Konsole and after a few days it started giving these messages on output:

`(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_move_resize_internal: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_process_updates: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_coords_to_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_effective_parent: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_get_position: assertion 'GDK_IS_WINDOW (window)' failed

(tilix:1892): Gdk-CRITICAL **: gdk_window_process_updates: assertion 'GDK_IS_WINDOW (window)' failed`

---

I am using Fedora 27 with 'updates-testing' repository enabled, so I'm getting lots of updates. Don't know if other system package is affecting it.

**Comment by diogocalgaro** [comment] 2017-12-26 13:05
I forgot to mention that the window that it happens is the one that I usually use the "sincronize input" feature.

I just discovered that when I click the "3 bar menu" button, all the terminals in the window come back to life for a few seconds. I can enter some command, but after 3 seconds it freezes. If I keep clicking the menu button, it keeps happening. But at some point, Tilix closes entirely.

**Comment by gnunn1** [comment] 2017-12-26 14:15
I'm not having any luck reproducing this, however I'll try enabling the synchronize terminals feature and see if I have more luck.

**Comment by fritjofbohm** [comment] 2017-12-29 09:54
I'm experiencing this, too. Of two terminals with synced inputs, only one survives, the other goes grey. Tilix 1.7.3, Fedora 27 with GNOME Shell 3.26.2.

When a tab enters the grey state, tilix gets very prone to crashing, but I guess that's a problem created by the underlying issue. See https://retrace.fedoraproject.org/faf/reports/1979703/ for a backtrace of the crash.

**Comment by gnunn1** [comment] 2017-12-29 17:06
@fritjofbohm Yeah unfortunately that backtrace is likely showing an effect of the original issue as I don't see anything in it related to this.

To reproduce this issue, do I just need to synchronize some terminals and leave tilix sitting there? I've been trying this with no luck reproducing it so far.

**Comment by gnunn1** [comment] 2017-12-29 17:08
Never mind, finally got it to happen. Looking into it now.

**Comment by gnunn1** [comment] 2017-12-29 17:35
Here's the thread dump I get. The synchronize input creates GDK events and it looks like there is a problem with it being freed properly by GtkD, either because of the way I'm doing things or something in the GtkD framework.

```
(tilix:10308): Gdk-WARNING **: losing last reference to undestroyed window

Thread 1 "tilix" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff54f4cd2 in ?? () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff54f4cd2 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff54fa421 in g_log_writer_default () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff54f4d72 in g_log_structured_array () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff54f515a in g_log_structured () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff3504710 in  () at /usr/lib/libgdk-3.so.0
#5  0x00007ffff57b86b5 in g_object_unref () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff34ea92f in gdk_event_free () at /usr/lib/libgdk-3.so.0
#7  0x0000555555ae38d8 in gdk.Event.Event.~this() (this=0x7ffff7f6f680) at Event.d:106
#8  0x0000555555e5e59e in rt_finalize2 ()
#9  0x0000555555e79dc8 in gc.impl.conservative.gc.Gcx.sweep() ()
#10 0x0000555555e76ea2 in gc.impl.conservative.gc.Gcx.fullcollect(bool) ()
#11 0x0000555555e78576 in gc.impl.conservative.gc.Gcx.smallAlloc(ubyte, ref ulong, uint) ()
#12 0x0000555555e751d4 in gc.impl.conservative.gc.ConservativeGC.runLocked!(gc.impl.conservative.gc.ConservativeGC.mallocNoSync(ulong, uint, ref ulong, const(TypeInfo)), gc.impl.conservative.gc.mallocTime, gc.impl.conservative.gc.numMallocs, ulong, uint, ulong, const(TypeInfo)).runLocked(ref ulong, ref uint, ref ulong, ref const(TypeInfo)) ()
#13 0x0000555555e77715 in _DThn16_2gc4impl12conservative2gc14ConservativeGC6mallocMFNbmkxC8TypeInfoZPv ()
#14 0x0000555555b69a3d in gobject.ObjectG.ObjectG.getDObject!(gdk.Event.Event, gdk.Event.Event, gdk.c.types.GdkEvent*).getDObject(gdk.c.types.GdkEvent*, bool) (obj=0x5555567dc350, ownedRef=false) at ObjectG.d:197
#15 0x0000555555c4ae1b in gtk.Widget.Widget.callBackFocusInEventGeneric(gtk.c.types.GtkWidget*, gdk.c.types.GdkEvent*, gtk.Widget.Widget.OnFocusInEventGenericDelegateWrapper) (widgetStruct=0x555556e145a0, event=0x5555567dc350, wrapper=0x7ffff7f22f40) at Widget.d:8116
#16 0x00007ffff39e338c in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff57ba6f5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff57ce0b0 in  () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff57d1efe in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff57d3920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff3b369e5 in  () at /usr/lib/libgtk-3.so.0
#22 0x00007ffff3b48968 in gtk_widget_send_focus_change () at /usr/lib/libgtk-3.so.0
#23 0x00007ffff3b4c527 in  () at /usr/lib/libgtk-3.so.0
#24 0x00007ffff3b4c7ea in  () at /usr/lib/libgtk-3.so.0
#25 0x00007ffff57b8e0a in g_cclosure_marshal_VOID__OBJECTv () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff57d2c01 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#27 0x00007ffff57d3920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#28 0x00007ffff57d2c01 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#29 0x00007ffff57d3920 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#30 0x00007ffff3b3a8ac in gtk_widget_grab_focus () at /usr/lib/libgtk-3.so.0
#31 0x00007ffff40ea011 in  () at /usr/lib/libvte-2.91.so.0
#32 0x00007ffff40fa1de in  () at /usr/lib/libvte-2.91.so.0
```

**Comment by gnunn1** [comment] 2017-12-29 17:53
I've checked in the change, could someone please double-check that this resolves the issue by either building tilix manually or using the arch ```tilix-git``` package.

**Closed** 2017-12-29 17:52 UTC
Labels: bug

**Comment by gnunn1** [comment] 2018-01-02 17:45
I realize it was the holidays, but just curious if anyone has had a chance to test this? If you need me to do a build for you to do so just let me know.

**Comment by diogocalgaro** [comment] 2018-01-02 17:55
I would really appreciate the build for testing. I tried to compile myself with no luck. :(

**Comment by gnunn1** [comment] 2018-01-03 00:09
@diogocalgaro Here you go:

http://gexperts.com/files/tilix.zip

**Comment by diogocalgaro** [comment] 2018-01-03 10:19
Thanks!

I am using this version now, running from Konsole. I am doing my regular workflow, where I have 4 or more sessions and with one of them I constantly use the "syncronized input" (I don't the original name, mine is pt_BR translated).

The gray terminals usually occurs after a few days, so I'll update you then.

**Comment by diogocalgaro** [comment] 2018-01-05 09:24
I think it has been running time enough to confirm that the problem is gone. No errors or warnings in Konsole (where I ran Tilix to get any output). So, I confirm it is solved to me :)

**Comment by gnunn1** [comment] 2018-01-05 14:12
That's great, thanks for testing it @diogocalgaro
