### ISSUE TITLE
Powerline (powerlevel9k) shows gaps between some segments only in Tilix

### ISSUE THREAD

**Issue by GabMus** [gnunn1/tilix#1383] opened 2018-04-20 13:28 UTC
When using Tilix with zsh+oh_my_zsh+powerlevel9k+nerd fonts there are 1px gaps between powerline segments. This shouldn't happen.

It's pretty difficult to explain this problem in words, refer to the screenshots below.

This issue only happens in Tilix, it's not present in other terminals like termite or konsole.

OS: Arch Linux, kernel 4.16.2-2-ARCH
DE: GNOME Shell 3.28.1
Shell: zsh 5.5.1

#### Tilix

![](https://i.imgur.com/aFD86FL.png)

#### Tilix (zoomed to highlight the problem)

![](https://i.imgur.com/a5aZ8oI.png)

#### Termite
![](https://i.imgur.com/O6CFKeF.png)

#### Konsole

![](https://i.imgur.com/Fq078NN.png)

**Comment by gnunn1** [comment] 2018-04-21 22:25
What about gnome-terminal, so you see the same behavior there?

**Comment by GabMus** [comment] 2018-04-23 00:34
No, it doesn't happen in gnome-terminal

![](https://i.imgur.com/QYTBp0k.png)

**Comment by gnunn1** [comment] 2018-04-23 00:41
I can reproduce however it seems specific to this font for some reason. I'm using Roboto Mono for Powerline Regular (i.e. the non nerd font) and it works fine. I'm looking into it a bit more but nothing obvious comes to mind for cause.

**Comment by gnunn1** [comment] 2018-04-23 00:46
I see the same thing in gnome terminal on my system BTW so at least for me it's not just tilix.

![screenshot from 2018-04-02 20-59-22](https://user-images.githubusercontent.com/9358238/39102018-2450c180-466e-11e8-8cf6-c458c06c8782.png)

**Comment by GabMus** [comment] 2018-04-23 01:06
You're right, in some color schemes it's visible even in gnome-terminal

![](https://i.imgur.com/pQ4Ue3b.png)

Maybe it's a bug in vte? I have tilix's vte tho.

**Comment by GabMus** [comment] 2018-04-23 01:07
Nope, just reverted to upstream vte, the problem is still there...

**Comment by gnunn1** [comment] 2018-04-23 01:10
So this looks like a VTE issue, if so please open a bug at http://bugzilla.gnome.com and close this one.

**Comment by gnunn1** [comment] 2018-04-26 04:52
I'm closing this as I believe it is a VTE issue or an issue with the font and not tilix.

**Closed by gnunn1** 2018-04-26 04:52 UTC

**Comment by ckotte** [comment] 2020-07-22 17:18
@GabMus Could you fix it?
