### ISSUE TITLE
Suggestion: Environment vars in badges

### ISSUE THREAD

**Issue by joshsouza** [gnunn1/tilix#1484] opened 2018-07-26 16:47 UTC
As a user coming from iTerm, I have become very accustomed to utilizing environment variables as part of my terminal badging. The way that iTerm handles this is by incorporating a function into my .zshrc file that executes `iterm2_set_user_var`. I'm not sure if a similar approach would work with Tilix, but I feel like it would be a boon to this tool to have.

**Comment by gnunn1** [comment] 2018-07-28 22:49
I think the issue is how this would get communicated to tilix as there is no clean way to communicate information to tilix. The best way would be via custom OSC codes, this is how vte.sh communicates cwd changes to the emulator. Unfortunately VTE at the moment doesn't expose a way to define custom OSC or pass arbitrary information to the enclosing terminal emulator. 

Reading proc/<pid>/environ is not going to work either since the environment variables are not updated to reflect what is set in the shell.

I do have an issue open with VTE for this and I'm hopeful it will happen at some point but until then I don't think there is much I can do about this.

I'm going to close this for now.

**Closed by gnunn1** 2018-07-28 22:49 UTC
Labels: Upstream, enhancement

**Comment by joshsouza** [comment] 2018-07-30 06:38
Thanks for the explanation! 🤞 for the VTE change
