### ISSUE TITLE
Tilix became transparent.

### ISSUE THREAD

**Issue by webmastak** [gnunn1/tilix#1257] opened 2018-01-15 23:12 UTC
After the update 1.7.5-1 the background of the tilix became transparent.
https://i.imgur.com/SupdGwC.png

**Comment by gnunn1** [comment] 2018-01-15 23:20
How did you install it, from a package? This usually happens when the resource file with the CSS that tilix requires doesn't get installed in the right location.

**Comment by webmastak** [comment] 2018-01-15 23:22
installed with AUR, tried to reinstall does not help.

**Comment by gnunn1** [comment] 2018-01-15 23:31
If you start tilix from gnome-terminal (with no other tilix instances running), does it show any errors? 

Anyone else on Arch having this issue?

**Comment by webmastak** [comment] 2018-01-15 23:32
when running tilix from gnome-terminal no errors

**Comment by webmastak** [comment] 2018-01-16 15:00
expect a patch or there is a solution?

**Comment by gnunn1** [comment] 2018-01-16 17:58
There's not much I can do since I cannot duplicate it and no one else appears to be reporting the issue as far as I can tell. Is the transparency slider in the profile you are using set appropriately, what happens if you slide it back and forth?

**Comment by webmastak** [comment] 2018-01-16 19:12
Is the transparency slider in the profile does not affect transparency(

**Comment by gnunn1** [comment] 2018-01-16 19:14
Are you using Gnome? Does changing the theme to Adwaita make any difference?

**Comment by webmastak** [comment] 2018-01-16 19:19
GNOME Shell 3.26.2
change the subject to Adwaita,  but the background is vseravno transparent

**Comment by mabod** [comment] 2018-01-19 06:47
No issues with tilix here. 
tilix-bin 1.7.5-1 running on up-to-date Manajaro Cinnamon desktop

**Comment by f2404** [comment] 2018-01-26 18:54
Tilix has also became transparent for me. Arch Linux, tilix-bin 1.7.5, Xfce DE.

**Comment by gnunn1** [comment] 2018-01-27 18:51
What is the output of ```tilix --version```, just want to see if you it's the patched tilix vte or the normal one.

**Comment by gnunn1** [comment] 2018-01-27 18:58
Oops, I can reproduce now

**Comment by gnunn1** [comment] 2018-01-27 19:24
I can only reproduce using VTE 0.51 which is an unreleased version, it works fine on VTE 0.50. What version of VTE are you guys using? The command ```tilix --version``` will show the version number.

**Comment by f2404** [comment] 2018-01-27 19:35
I'm using vte3-git which is 0.51 currently.

**Comment by mabod** [comment] 2018-01-27 20:21
I have 
        Tilix-Version:  1.7.5
	VTE-Version: 0.50
	GTK-Version: 3.22.26

No issues.

**Comment by gnunn1** [comment] 2018-01-27 20:30
I just checked in a fix for this, please test. The problem was an inconsistent check for a future API was causing tilix to use a clear background.

**Comment by webmastak** [comment] 2018-01-28 15:26
Did not help  ((

Tilix: 1.7.5
VTE: 0.51
 GTK: 3.22.26

**Comment by webmastak** [comment] 2018-01-28 20:43
Yes version 1.7.6-0.0.1 master.tar.gz fixed :+1: 
Thank you!

**Comment by bwat47** [comment] 2018-02-03 18:00
In the meantime, a workaround is to just create a .png image that's solid your desired color and set that as the bg in the tilix preferences

**Comment by gnunn1** [comment] 2018-02-03 23:18
@ceyhunnabiyev If you are using a pre-release of VTE then please use tilix-git from AUR, I'm not planning on doing a release just for this.

**Comment by ceyhunnabiyev** [comment] 2018-02-04 08:13
But this is a serious problem. Tilix is transparent, any option for this doesn't work. It would be nice to  release like 1.7.5.1. I don't use git version of packages, because they are developing versions.

**Comment by bwat47** [comment] 2018-02-04 13:31
Is VTE 0.51 a pre-release? It looks like it was first released back in November 2017: https://github.com/GNOME/vte/releases/tag/0.51.1

Also it's now in the stable arch and manjaro repos...

In any case, as a Workaround, I've found that you can create a png image with your desired background color, and then go to preferences | appearance and select that image as your background.

**Comment by ceyhunnabiyev** [comment] 2018-02-04 13:46
I have vte3 0.51.3 version in Manjaro.

**Comment by dsboger** [comment] 2018-02-04 14:05
@ceyhunnabiyev It is certainly not the case for [vte3](https://www.archlinux.org/packages/extra/x86_64/vte3/) package in Arch Linux. Sorry, but you are in a kind of "no support" situation. Even then, you have a few promising options.

But more importantly, this is **not** an upstream issue anymore. Please, move the discussion either to AUR or to Manjaro support.

**Comment by gnunn1** [comment] 2018-02-04 14:10
The odd number releases of VTE are pre-release versions, the even numbers are release versions. So 0.49 was the pre-release for 0.50. 

What package exactly are you using in Arch and Manjaro that is supplying 0.51?

**Comment by bwat47** [comment] 2018-02-04 14:30
In Manjaro I just got it as a stable update https://gist.githubusercontent.com/philmmanjaro/5434baac29afea414436393da159aadd/raw/5753d4bd21374945134eed84834a61e9422395bd/boxit-stable-2018-02-03.txt

**Comment by gnunn1** [comment] 2018-02-04 14:46
I think you would have to ask the Manjaro folks why they are releasing pre-release versions of VTE as stable.

**Comment by ceyhunnabiyev** [comment] 2018-02-04 14:50
I asked, @gnunn1. Really sorry for stupid request and wasting your time.

**Comment by gnunn1** [comment] 2018-02-04 15:15
@ceyhunnabiyev You are not wasting anyone's time so no worries. It's good to know where the problem is coming from, hopefully someone follows up with the Manjaro folks. if they do, feel free to link it here and I'll keep an eye on it.

**Comment by webmastak** [comment] 2018-02-04 19:28
It would be good if the tilix were added to the official repository of Manjaro!

**Comment by cortopy** [comment] 2018-02-05 10:21
installing `tilix-git` in manjaro fixed it for me. Thanks!

**Comment by focmb** [comment] 2018-02-05 10:45
running tilix-git from AUR with gnome 3 and tilix is always transparent. I have to set a drak background as a workaround.

Versionen
	Tilix-Version:  1.7.5
	VTE-Version: 0.51
	GTK-Version: 3.22.26

**Comment by phw** [comment] 2018-02-05 10:48
@focmb Have you updated the tilix-git package to the latest revsion? What is the output of `pacman -Qi tilix-git`?

**Comment by webmastak** [comment] 2018-02-05 11:58
Who does not help:
`
$ yaourt tilix
`
select item 2
select edit PKGBUILD

copy:
`
# https://github.com/gnunn1/tilix/archive/master.tar.gz

pkgname="tilix"
pkgver=1.7.5
pkgrel=1
pkgdesc="A tiling terminal emulator for Linux using GTK+ 3"
arch=('x86_64' 'i686')
url="https://github.com/gnunn1/tilix"
license=('MPL')
depends=('libx11' 'gtkd' 'vte3' 'dconf' 'gsettings-desktop-schemas')
makedepends=('ldc' 'po4a')
optdepends=('python2-nautilus: for "Open Tilix Here" support in nautilus'\
            'vte3-notification: for desktop notifications support'\
            'vte3-tilix: for notifications, triggers and badges support'
            'libsecret: for the password manager')
provides=('terminix')
conflicts=('terminix')
replaces=('terminix')
source=("$url/archive/master.tar.gz")
sha256sums=('e0e645d017f97210f4c50e829e0620fe3f4fdfa8410df3a8dc208db59b2b2275')


prepare() {
    cd "$pkgname-master"
    ./autogen.sh
}

build() {
    cd "$pkgname-master"
    ./configure --prefix=/usr PO4A_TRANS=/usr/bin/vendor_perl/po4a-translate DC='ldmd' DCFLAGS='-O -inline -release -version=StdLoggerDisableTrace -defaultlib=phobos2-ldc-shared,druntime-ldc-shared'
    make
}

package() {
    cd "$pkgname-master"
    make DESTDIR="$pkgdir" install
}
`

**Comment by egmontkob** [comment] 2018-02-05 13:13
We use the term "unstable" at GNOME, rather than "unreleased" or "pre-release" but that's just playing with words, the point is the same.

Stable vte-0.52 (along with entire GNOME 3.28) is scheduled to be released on [March 14](https://wiki.gnome.org/ThreePointTwentyseven). I think it would be nice to have a new Tilix release by then, or shortly afterwards the latest. @gnunn1 is absolutely right that it shouldn't be expected from Tilix to support/workaround unstable VTE versions.

**Comment by gnunn1** [comment] 2018-02-05 13:25
I'm re-opening this just as informational. With regards to @egmontkob point, yes there will be a new tilix release well before March 14.

**Comment by focmb** [comment] 2018-02-05 14:29
pacman -Qi tilix-git gives me:

`Name                     : tilix-git
Version                  : 1.7.5.r0.bf89176-1
Beschreibung             : A tiling terminal emulator based on GTK+ 3 (git master)
Architektur              : x86_64
URL                      : http://github.com/gnunn1/tilix
Lizenzen                 : MPL
Gruppen                  : Nichts
Stellt bereit            : terminix  tilix
Hängt ab von             : libx11  gtkd  vte3  dconf  gsettings-desktop-schemas
Optionale Abhängigkeiten : python2-nautilus: for "Open Tilix Here" support in nautilus [Installiert]
                           vte3-notification: for desktop notifications support
                           vte3-tilix: for notifications, triggers and badges support
                           libsecret: for the password manager [Installiert]
Benötigt von             : Nichts
Optional für             : Nichts
In Konflikt mit          : terminix  tilix
Ersetzt                  : Nichts
Installationsgröße       : 3,99 MiB
Packer                   : Unknown Packager
Erstellt am              : Fr 12 Jan 2018 20:35:37 CET
Installiert am           : Fr 12 Jan 2018 20:35:39 CET
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Nichts`

**Comment by phw** [comment] 2018-02-05 14:31
@focmb The version 1.7.5.r0.bf89176-1 indicates that you are exactly on the 1.7.5 release, the fix for this was later. Please rebuild the tilix-git package.

**Comment by ceyhunnabiyev** [comment] 2018-02-05 15:10
@gnunn1 
> I think you would have to ask the Manjaro folks why they are releasing pre-release versions of VTE as stable.

I can't get a correct answer, seems like "no reason" :smile: . Anyway I reinstalled tilix with this fix. Thanks..

**Comment by focmb** [comment] 2018-02-05 15:42
Thanks. I will try it. But now tilix-git is not in the AUR anymore. I found tilix 1.7.5-1. I willtest this version.

**Comment by dsboger** [comment] 2018-02-05 15:49
@focmb tilix-git (and every *-git package) should update its version while you build/install it. Please, give it a try and report in AUR if you have any trouble!

**Comment by chrisvel** [comment] 2018-02-05 20:06
I confirm tilix-git works fine for me and the same problem running Manjaro.

**Comment by ceyhunnabiyev** [comment] 2018-02-06 14:11
@chrisvel , Manjaro use Pre-release version of vte3. That is why.

**Comment by mabod** [comment] 2018-02-06 14:46
For all the Manjaro users: Just install 
```
vte-notification-common 0.50.2-1
vte3-notification 0.50.2-1
```
and get rid of the vte 0.51 stuff.

**Comment by ceyhunnabiyev** [comment] 2018-02-07 07:40
Thanks..

**Comment by PrzemekSkw** [comment] 2018-02-07 08:33
@mabod Thanks, works on Manjaro Deepin too :)

**Comment by dsboger** [comment] 2018-02-08 12:37
@mabod good call! You can also use `vte3-tilix` and `vte-tilix-common`, which enable a few more bells and whistles, like [badges](https://gnunn1.github.io/tilix-web/manual/badges/) and [triggers](https://gnunn1.github.io/tilix-web/manual/triggers/).

**Comment by themindfulcoder** [comment] 2018-02-19 05:58
FYI

This just happened to me on ubuntu bionic alpha 2 - budgie desktop with developer option enabling pre-releases

tilix version 1.7.5
VTE version 0.51
GTK version 3.22.28

**Comment by egmontkob** [comment] 2018-02-19 09:04
VTE received an [API change](https://git.gnome.org/browse/vte/commit/?id=bc532dc160406aaea35756e9a9e8f755c82fddb2) just before its 0.51.90 release (the beginning of the API freeze). Tilix currently uses a method that was an unstable one during the 0.51 series, and ended up getting removed (replaced by a different one). Tilix is yet to be updated against the new API.

**Comment by egmontkob** [comment] 2018-02-19 09:04
[Ubuntu downstream bugreport](https://bugs.launchpad.net/ubuntu/+source/tilix/+bug/1750322)

**Comment by fossfreedom** [comment] 2018-02-19 12:56
would applying this commit fix this issue for v1.7.5 - or does the API change @egmontkob refers to require another fix?

https://github.com/gnunn1/tilix/commit/3a7d8e0d31eba62e4bbef0f68006ea28e2a93a0d

**Comment by egmontkob** [comment] 2018-03-12 22:00
FYI: vte-0.52 is out now.

> there will be a new tilix release well before March 14

ahem-ahem :D

**Comment by gnunn1** [comment] 2018-03-12 22:04
Lol, it's not the last minute, I still have time! 🙂

**Comment by gnunn1** [comment] 2018-03-13 00:40
1.7.7 pushed out the door, was hoping to get more done in this release but no time. These days I'm pretty much in maintenance mode on tilix.

**Comment by bear454** [comment] 2018-03-19 23:50
Workaround (until your distro package catches up): add a tiled background image, for example:

[solarized-dark-bg-1px.png](https://user-images.githubusercontent.com/108494/37628174-8f1989d2-2b95-11e8-8430-393efe1581ab.png)

**Comment by gnunn1** [comment] 2018-04-03 23:03
This has been fixed, closing issue.

**Closed by gnunn1** 2018-04-03 23:03 UTC
Labels: bug
