### ISSUE TITLE
Segmentation Fault on start (Fedora 26)

### ISSUE THREAD

**Issue by HarryPhoon** [gnunn1/tilix#1146] opened 2017-10-08 12:55 UTC
Few days ago I tried to open Tilix quake and nothing happend, so I tried to open normal application but it did not start. So I ran it from Terminal and got just "Segmentation fault (core dumped)" (https://imgur.com/8Mb8SgU).
Checked if there was some update that could change something but apart from basic system update and probably uninstalling and installing powerline shouldn't be anything the cause. (checked with dnf history)
Already tried to reinstall. Still the same.

tilix version:
```
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.21

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```

gdb:
```
(gdb) run
Starting program: /usr/bin/tilix 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe2580700 (LWP 6198)]
[New Thread 0x7fffe1d7f700 (LWP 6199)]
[New Thread 0x7fffe155a700 (LWP 6200)]

Thread 1 "tilix" received signal SIGSEGV, Segmentation fault.
0x00007ffff76695d9 in gtk.StyleContext.StyleContext.addProviderForScreen(gdk.Screen.Screen, gtk.StyleProviderIF.StyleProviderIF, uint) (
    screen=<optimized out>, provider=0x7ffff7ec19a0, priority=600)
    at StyleContext.d:202
202	StyleContext.d: No such file or directory.
```

**Comment by gnunn1** [comment] 2017-10-08 20:11
I think this is a duplicate of #1144, check what version of GtkD you have installed. If it is 1.6.6 then it likely is the same issue.

**Closed by gnunn1** 2017-10-08 20:11 UTC

**Comment by HarryPhoon** [comment] 2017-10-11 18:26
```
rpm -q gtkd
gtkd-3.6.6-1.fc26.x86_64
```
