### ISSUE TITLE
Flatpack Install fails to lauch from gnome shell (application menu)

### ISSUE THREAD

**Issue by sferich888** [gnunn1/tilix#1576] opened 2018-11-08 04:22 UTC
```
Nov 07 22:40:13 HOSTNAME dbus-daemon[1441]: [session uid=1000 pid=1441] Activating service name='com.gexperts.Tilix' requested by ':1.8' (uid=1000 pid=1544 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Nov 07 22:40:13 HOSTNAME systemd[1419]: Started flatpak-com.gexperts.Tilix-3440.scope.
Nov 07 22:40:14 HOSTNAME com.gexperts.Tilix[1441]: bwrap: execvp /usr/bin/tilix: No such file or directory
Nov 07 22:40:14 HOSTNAME dbus-daemon[1441]: [session uid=1000 pid=1441] Activated service 'com.gexperts.Tilix' failed: Process com.gexperts.Tilix exited with status 1
```
This issue seems to be caused by how gnome is starting or trying to start tilix, from `/var/lib/flatpak/app/com.gexperts.Tilix/x86_64/master/active/files/share/dbus-1/services/com.gexperts.Tilix.service` however I have not been able to get this behavior to change, but editing this file. 

I am able to start the flatpack using the cli, `flatpak run com.gexperts.Tilix`, but I can't start it using gnome. 

$ gnome-shell --version
GNOME Shell 3.30.1
$ flatpak --version
Flatpak 1.0.4

**Comment by kirbyfan64** [comment] 2018-11-08 04:57
Do you have normal Tilix installed as well? I recall this happening at one point when both the rpm and flatpak were installed, so I had assumed it was a GNOME issue, but I haven't tested in a while.

**Comment by sferich888** [comment] 2018-11-08 05:03
I do not. 
With Silverblue you have to mess with the rpmos-tree to get packages installed (I'm trying to avoid that).

**Comment by sferich888** [comment] 2018-11-11 12:30
The issue is with `export/share/dbus-1/services/com.gexperts.Tilix.service`

```
D-BUS Service]
Name=com.gexperts.Tilix
Exec=/usr/bin/flatpak run --branch=master --arch=x86_64 --command=/usr/bin/tilix com.gexperts.Tilix --gapplication-service~
```

This should just be `--command=tilix`

**Comment by bilelmoussaoui** [comment] 2018-11-11 12:55
@sferich888 It was already fixed on master https://github.com/gnunn1/tilix/blob/master/data/dbus/com.gexperts.Tilix.service.in#L3

**Comment by bilelmoussaoui** [comment] 2018-11-29 09:14
The issue is that the Flatpak manifest still uses autotools, this issue was fixed with meson only. We should update the manifest to use the meson buildsystem instead.

**Comment by sferich888** [comment] 2021-11-12 01:37
I think this original issue is fixed but... the flat pack still has issues (example: https://github.com/containers/toolbox/issues/886)

**Closed** 2023-04-03 17:55 UTC
Labels: bug
