### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by alvesadrian** [gnunn1/tilix#1546] opened 2018-10-08 05:37 UTC
~ ❯❯❯ sudo su -
-bash: __git_ps1: command not found
-bash: __vte_osc7: command not found
[root@x230 ~]# 

workaround doc didnt work on latest arch with zsh (prezto)

**Comment by gnunn1** [comment] 2018-10-10 01:40
I think the problem is the root user is set to use bash while your personal user is set to use zsh. I'm not sure it is a good idea to change the root user to zsh, I would suggest asking about it on a zsh forum. 

This is not a tilix issue as far as I can tell so closing the issue.

**Closed by gnunn1** 2018-10-10 01:40 UTC

**Comment by adrian-gluu** [comment] 2018-10-10 18:29
root is using bash only my user is on zsh
