### ISSUE TITLE
Delay when opening Quake mode

### ISSUE THREAD

**Issue by p-e-w** [gnunn1/tilix#1178] opened 2017-11-05 13:54 UTC
(Fedora 26 with GNOME on Wayland with animations disabled, Tilix 1.7.1)

There is a noticeable lag (~ 200 ms) between pressing the hotkey and the dropdown terminal appearing. Guake does not have this problem.

Not sure how much of this is due to the compositor and indeed whether there is anything you can do about it. I am aware that Guake uses keybinder which does not work with Wayland. Perhaps the lag is nothing more than the process being launched each time. Nevertheless, I find it a bit distracting and decided to open an issue since there doesn't seem to be one already.

**Comment by gnunn1** [comment] 2017-11-05 23:29
I cannot reproduce this on Arch Linux running Gnome on Wayland. What's the output of ```tilix --version```? Also, if you open gnome-terminal and run ```tilix --quake``` from there do you notice the same delay, tilix uses DBusActivation by default so that could be causing it as well.

BTW thanks for your work on finalterm, it was a great project.

**Comment by klingtnet** [comment] 2017-11-06 10:23
I can confirm this on X11:

```sh
$ tilix --version
Versions
	Tilix version: 1.7.1
	VTE version: 0.50
	GTK Version: 3.22.25

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

The lag on my machine is notably longer than 200ms, more in the range of one to a couple of seconds.
Restarting tilix helps, though.

**Comment by klingtnet** [comment] 2017-11-06 10:29
Here is a zipped ([tilix-quake-delay.zip](https://github.com/gnunn1/tilix/files/1445858/tilix-quake-delay.zip)) demonstration video where I open and close tilix two times. Note that I immediately pressed my tilix quake mode shortcut after closing it.

**Comment by klingtnet** [comment] 2017-11-06 10:30
Maybe some additional information, resetting my Gnome configuration to defaults and disabling all extensions does not help.

**Comment by klingtnet** [comment] 2017-11-06 10:41
This is the output of `$ dbus-monitor` when closing and opening tilix in quake mode:
[tilix-dbus.log](https://github.com/gnunn1/tilix/files/1445890/tilix-dbus.log)

journalctl does not show anything suspicious which is why I don't paste it here.

**Comment by klingtnet** [comment] 2017-11-06 10:42
I just installed `tilix-git` but the issue is still there.

**Comment by klingtnet** [comment] 2017-11-06 10:45
Maybe a last addition, tilix starts immediately in _normal_ mode (not as drop-down).

**Comment by gnunn1** [comment] 2017-11-06 13:31
If you run tilix --quake from gnome-terminal is there a delay? If there is not, try disabling dbus activation in the desktop file.

**Comment by klingtnet** [comment] 2017-11-06 13:36
@gnunn1 It takes the same time to open.

> ... disabling dbus activation in the desktop file.

How can I do that?

**Comment by klingtnet** [comment] 2017-11-06 13:42
Here is the strace:
[tilix-strace.log](https://github.com/gnunn1/tilix/files/1446359/tilix-strace.log)

It waits at line `poll([{fd=10, events=POLLIN}], 1, 25000) = 1 ([{fd=10, revents=POLLIN}])`.

**Comment by fbernier** [comment] 2017-11-06 15:42
I also get this on archlinux:

```
Versions
        Tilix version: 1.7.1
        VTE version: 0.50
        GTK Version: 3.22.25

Tilix Special Features
        Notifications enabled=0
        Triggers enabled=0
        Badges enabled=0
```

It seems like it redraws every time I hide/show. Vim moves around to get back into fullscreen each time.

**Comment by gnunn1** [comment] 2017-11-08 02:02
@klingtnet You can edit the tilix desktop file, ```com.gexperts.Tilix.desktop```, and change ```DBusActivatable=true``` to ```DBusActivatable=false```.

**Comment by klingtnet** [comment] 2017-11-08 08:29
@gnunn1 This fixed the issue, thank you very much!

**Comment by klingtnet** [comment] 2017-11-08 12:18
Restarting the gnome-shell session fixed it. So the problem is probably caused on the Gnome side.

**Comment by klingtnet** [comment] 2017-11-08 12:32
I've just created an issue in Gnome's bug tracker: https://bugzilla.gnome.org/show_bug.cgi?id=790059

**Comment by gnunn1** [comment] 2017-11-08 13:14
Thanks, closing issue as upstream.

**Closed by gnunn1** 2017-11-08 13:14 UTC
Labels: bug, Can't Reproduce

**Comment by p-e-w** [comment] 2017-11-11 06:53
@gnunn1 Apologies for the delay (no pun intended), some more details:

> What's the output of `tilix --version`?

```
$ tilix --version
Versions
	Tilix version: 1.6.4
	VTE version: 0.48
	GTK Version: 3.22.21

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=0
```

(Contradicting my original claim that I had Tilix 1.7.1, sorry for the confusion.)

> Also, if you open gnome-terminal and run `tilix --quake` from there do you notice the same delay

Yes.

> try disabling dbus activation in the desktop file.

Hard to say whether this makes a difference because it is so difficult to measure the delay precisely. The one thing that is certain is that in all cases, the delay is substantially greater than it ever was with Guake.

Unlike @klingtnet there doesn't appear to be an issue with GNOME Shell in my case as it happens every time, even after a full system restart (restarting GNOME Shell alone is not possible on Wayland). Then again, as mentioned I do not experience multi-second delays, only 100-200 ms.

> BTW thanks for your work on finalterm, it was a great project.

Thank you, and thank you for creating Tilix! There has been much change in the world of terminal emulators in the past few years, fuelled by the meteoric rise of macOS (and thus iTerm2), web experiments like Hyper and Black Screen, the appearance of Tilix and its rapid adoption among GNOME users, and the upstart Alacritty.

As a Linux user, I was always jealous of iTerm2 and its huge array of features, but I now consider Tilix to be even better (VTE was always much better than iTerm2 performance-wise, but GNOME Terminal is pretty barebones). It's quite amazing what you have built here in such a short time, and how quickly you always respond to issues and resolve them! There are very few Linux Desktop projects today that I would consider to be on par with Tilix quality-wise.

In the long term, I am placing my faith in Alacritty for emulation, because its superior performance, code infrastructure, and the fact that it runs on macOS are bound to give it the momentum to steamroll all others eventually. The author however refuses to add "advanced" features such as tabs and splits, which is why I view Alacritty more as a backend and hope that it might be able to replace VTE in Tilix in the far future. I have already opened an issue to this effect [here](https://github.com/jwilm/alacritty/issues/450).

**Comment by simontong** [comment] 2020-04-13 06:15
I'm getting this issue on KDE + Arch Linux. It takes about 400ms for quake mode to appear.

```
Versions
	Tilix version: 1.9.1
	VTE version: 0.60
	GTK Version: 3.24.17

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```
