### ISSUE TITLE
 tilix --action session-add-down --focus-window under wayland: not working

### ISSUE THREAD

**Issue by arigit** [gnunn1/tilix#932] opened 2017-05-19 04:50 UTC
Couldn't re-open #839, unfortunately the same issue is still there in Fedora 25 and Tilix 1.5.6, under Wayland

To reproduce: 
- open a tilix window
- focus on some other window, e.g. nautilus or firefox
- press Alt-F2 to get an "enter a command" prompt, and execute this command:
 tilix --action session-add-down --focus-window -e bash

The end result is: a new terminal is added in the existing tilix window, but the tilix window and all its terminals remain unfocused. I would have expected that focus would move to the tilix window and within it to the newly created terminal 

As explained in #839, my actual use case is using desktop files within nautilus, to launch commands (some of them interactive). The said .desktops are setup up to open a new tilix terminal within an existing tilix window, and supposedly to set the focus. However, setting the focus fails.

In Preferences, I tried setting Global > On new instance > "Focus Window", and also all other options, but the use case above still fails in the exact same manner

**Comment by gnunn1** [comment] 2017-05-19 12:29
So the issue is only with it setting focus correct, everything else works OK? If so, there's nothing I can do about it as Wayland does not allow me to control the focus of the window. In GTK I believe the window.present() method is essentially a NO-OP.

**Comment by arigit** [comment] 2017-05-19 13:46
Yes I checked other recent fixes and they are working. Just the focus annoyance.
I found some references on how to set focus to an existing GTK:window, e.g.

https://www.ruby-forum.com/topic/125408

It's ruby but I'm guessing any language binding would support this - although not sure if it applies to tilix's use case.

For reference, interesting discussion on xdotool & wayland
https://github.com/bulletmark/libinput-gestures/issues/37

Question - is tilix using XWayland windows or native wayland? if XWayland, xdotool windowfocus would work as a temp workaround

**Comment by arigit** [comment] 2017-05-19 14:23
Sorry for the spam. This seems to be more related to the method you are trying to use:

 [Wayland] gtk_window_present() not working
https://bugzilla.gnome.org/show_bug.cgi?id=766284

not a clean workaround, but perhaps worth a try until they fix this.

> It works if I call gtk_window_present_with_time() with the current time.
> Let's do that I guess.

**Comment by gnunn1** [comment] 2017-05-19 15:03
@arigit I've already tried the gtk_window_present_with_time(), it didn't work for me in my testing.

Tilix is using native Wayland and not XWayland. You can force it to use XWayland as follows:

```
GDK_BACKEND=x11 tilix
```

Assuming no other instances of tilix are running.

**Comment by bil-elmoussaoui** [comment] 2017-05-19 15:08
@gnunn1 Lollypop implemented the same fix as proposed by @arigit and it works just fine in my case

**Comment by gnunn1** [comment] 2017-05-19 15:12
I can try putting it back in, however in my case it did not seem to work. Quite possible I implemented something wrong though. @bil-elmoussaoui do you know which commit that was implemented in for lollypop?

**Comment by bil-elmoussaoui** [comment] 2017-05-19 17:00
https://github.com/gnumdk/eolie/commit/478aed05b1ec43e6af66e5194845bcc3c4c820ba

**Comment by gnunn1** [comment] 2017-05-19 21:51
I've checked in the change to use presentWithTime but it doesn't make any difference for me. Please try it out and see if it helps you at all.

**Comment by gnunn1** [comment] 2017-05-22 21:57
As anyone had a chance to test this?

**Comment by arigit** [comment] 2017-05-23 13:46
I tested the workaround of using 
`env GDK_BACKEND=x11 tilix`

for every scripted call and all my shortcuts and that worked.

I don't have a fedora build environment in the workstation so wondering if is there any chance you can leave the commit so it makes it to the fedora COPR for greater exposure?

Thanks! /A

**Comment by gnunn1** [comment] 2017-05-23 15:47
I'll leave the commit in so it can be tested. I'm closing this issue for now as I don't have any further ideas to address this.

**Closed by gnunn1** 2017-05-23 15:47 UTC
Labels: bug, Upstream
