### ISSUE TITLE
Terminal title not working with hostname with dot

### ISSUE THREAD

**Issue by fhfournier** [gnunn1/tilix#1526] opened 2018-09-18 14:17 UTC
If i use ${title} as TerminalTitle its not showing the full title. If hostname contain dot this break after that

Its supose to be "username@host.com" and the title showing "username@host"

**Comment by gnunn1** [comment] 2018-09-18 14:42
The problem is vte.sh truncates the hostname, interestingly it only does this for Bash and not for ZSH. You should see the exact  same behavior from gnome-terminal.  I've opened an issue upstream for this:

https://gitlab.gnome.org/GNOME/vte/issues/49

**Comment by fhfournier** [comment] 2018-09-19 13:05
And even if i connect with SSH it should work? Without modify the remote file  ~/.bashrc 

There is something i could do to fix this?

**Comment by gnunn1** [comment] 2018-09-19 13:33
You need to modify vte.sh to change the ```${HOSTNAME%%.*}``` to ```${HOSTNAME:-}``` in the function ```__vte_prompt_command()```. However note making this change will only last until the next time VTE gets updated then it will be replaced.

vte.sh is not part of Tilix, it is part of the VTE widget that is providing the terminal emuation that tilix uses. This is the same widget that gnome-terminal and other terminal emulators use. As a result I'm closing this issue because it's not a tilix issue and I've opened an issue for it upstream.

**Closed by gnunn1** 2018-09-19 13:33 UTC
Labels: Upstream, bug
