### ISSUE TITLE
Tilix crash when opening window in quake mode

### ISSUE THREAD

**Issue by danleepw** [gnunn1/tilix#1462] opened 2018-07-09 03:35 UTC
$> tilix --version
Versions
	Tilix version: 1.8.1
	VTE version: 0.42
	GTK Version: 3.18.9

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0

$> tilix -q  
object.Error@(0): The function you are calling is not pressent in your version of GTK+.
??:? extern (C) void gtkd.Loader.Linker.unsupportedSymbol() [0xd6283483]
??:? gdk.MonitorG.MonitorG gdk.Display.Display.getMonitor(int) [0xd6233f00]
??:? [0x610e09]
??:? [0x61084b]
??:? g_closure_invoke [0xd2f58fa4]
??:? [0xd2f6afc0]
??:? g_signal_emit_valist [0xd2f73d5b]
??:? g_signal_emit [0xd2f7408e]
??:? gtk_widget_realize [0xcb992d5b]
??:? [0xcb99fc57]
??:? g_closure_invoke [0xd2f58fa4]
??:? [0xd2f6aafb]
??:? g_signal_emit_valist [0xd2f73d5b]
??:? g_signal_emit [0xd2f7408e]
??:? gtk_widget_show [0xcb98f714]
??:? [0x617384]
??:? g_closure_invoke [0xd2f58fa4]
??:? [0xd2f6afc0]
??:? g_signal_emit_valist [0xd2f73d5b]
??:? g_signal_emit [0xd2f7408e]
??:? [0x616af6]
??:? extern (C) void gobject.DClosure.DClosure.d_closure_marshal!(int delegate(glib.c.types.Scoped!(gio.ApplicationCommandLine.ApplicationCommandLine).Scoped, gio.Application.Application)).d_closure_marshal(gobject.c.types.GClosure*, gobject.c.types.GValue*, uint, gobject.c.types.GValue*, void*, void*) [0xd60bcbec]
??:? g_closure_invoke [0xd2f58fa4]
??:? [0xd2f6afc0]
??:? g_signal_emit_valist [0xd2f737f8]
??:? g_signal_emit [0xd2f7408e]
??:? [0xd24e3ac2]
??:? [0xd24e5b1c]
??:? g_application_run [0xd24e5ce1]
??:? [0x61b79a]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0xd4ba269e]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0xd4ba25dd]
??:? _d_run_main [0xd4ba24d8]
??:? __libc_start_main [0xd456782f]
??:? [0x588ce8]

**Comment by rpr13** [comment] 2018-07-09 08:07
I have same error.

OS - Ubuntu 16.04.4 LTS
Tilix - 1.8.1
VTE - 0.42
GTK - 3.18.9
WM - xfce4 - xfwm4 4.12.3

It began after update.
ppa:webupd8team/terminix

**Comment by gnunn1** [comment] 2018-07-09 11:13
Duplicate of #1457

**Closed by gnunn1** 2018-07-09 11:13 UTC
