### ISSUE TITLE
Weird top behavior on Debian Stretch

### ISSUE THREAD

**Issue by c0de123** [gnunn1/tilix#1122] opened 2017-09-13 07:12 UTC
Hi,
I installed tilix from stretch backports and when I am running top, the screen starts to "flicker" - meaning I can only see alternating lines from top, making it appear like flashing. It seems that the refreshing behavior of top is causing issues within tilix.
I have the same issue on Ubuntu 17.04. Here, tilix is installed from webupd8.
It would be nice if someone could help me with this as this is really annoying and stopping me from finally switching over to tilix.

Thanks!

**Comment by gnunn1** [comment] 2017-09-13 16:06
What video card and driver are you using?

If you disable transparency in dconf (under /com/gexperts/Tilix) does that make any difference?

**Comment by c0de123** [comment] 2017-09-13 17:31
On the debian system:

GPU:
`00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)`

Driver:
`i915`

`enable-transparency` set to `False` => same behavior :(

The other system has an intel GPU, too, so probably also using the i915 driver.

**Comment by gnunn1** [comment] 2017-09-13 23:47
Did you try to disable the transparency as suggested above?

**Comment by gnunn1** [comment] 2017-09-13 23:47
Oops ignore last, missed that you did

**Comment by gnunn1** [comment] 2017-09-13 23:48
What's the output of ```tilix --version```?

**Comment by c0de123** [comment] 2017-09-14 04:21
On Debian, it is
`1.6.4-1~bpo9+1`
Ubuntu, I will post later.

**Comment by stullii** [comment] 2017-09-14 13:19
Same happens to me (Debian Stretch, Mate DE, Tilix 1.6.4, top), you can see it here: https://www.dropbox.com/s/pjcvxo1g9y5a6l8/tilix.ogv?dl=0

**Comment by egmontkob** [comment] 2017-09-14 19:00
Seems like every second line is empty. (First I thought about some extra vertical padding in the font, but then the cursor would be much taller too.)

Could you please confirm that if you `cat` some text file (e.g. `cat /etc/services`), or simply type a long command that wraps to the next line then the lines have double density compared to this video?

What do other fullscreen apps, such as `mc`, `vim`, `htop` or whichever occurs to you do?

What's the behavior of `top` in `gnome-terminal` or some other libvte-2.91 based terminal?

I can see decimal commas in your screenshot. Maybe some other locale issue messes with `top`. What are your locale settings? Could you please try `export LC_ALL=en_US.UTF-8` and then `top`?

I believe that for whatever reason, `top` outputs one more character (or a few more characters) per line than the width of the terminal. We're yet to investigate if it's a bug in `top`, or `vte` reports incorrect size.

**Comment by c0de123** [comment] 2017-09-15 06:02
I still think it is a problem with "refreshing lines".
As I said before, the apt progress bar also behaves strange sometimes. I just installed `htop` and this was the result of the progress bar in the terminal:
`Reading state information... Done#########################################....] `
Mind that this was the line after `htop` was completed.
I don't have any problems in `vim`, `htop` also runs as expected.
Using `cat` on long text lines shows what you expect. Exporting `LC_ALL=en_US.UTF-8` also didn't help.

**Comment by egmontkob** [comment] 2017-09-15 08:17
Let's stick with one particular app for investigation and let's choose `top`. (This is beacuse with `apt` you'd need to perform something else every time, also you said it misbehaved "sometimes". Plus it might not be available on other developers' machines.)

Does `top` always work incorrectly for you? Try manually resizing the Tilix window and running `top` afterwards, is it still broken?

Do you have an `/etc/toprc` or `~/.toprc`? If so, please share with us (or try to reproduce without).

Could you please test the following for me: run `stty size` and `echo $COLUMNS` (and tell us what they report) as well as manually count the number of available columns, e.g. run `cat` and copy-paste `1234567890` repeatedly until it overflows to the next line; what's the last digit in the initial line, and what's the first digit in the next line? (At this point I wouldn't be _that_ surprised seeing a mismatch.)

Also please do the following: staying with the same window size as in the previous step, run `script`, then run `top`, then press `q` as soon as you notice the buggy behavior, then press `ctrl+D` to exit from `script`, and finally attach the created `typescript` file?

What does `echo $TERM` report? You don't have any screen/tmux running, do you?

Please also don't forget to test it in `gnome-terminal` or some other libvte-2.91 based terminal (e.g. if `ldd /usr/bin/mate-terminal | grep vte` reports `libvte-2.91.so.0` then it's also recent enough). By the way, what happens in other completely different terminal emulators such as e.g. `xterm`, `urxvt` or `konsole`?

Thanks!

**Comment by c0de123** [comment] 2017-09-15 08:32
Maximizing makes no difference in behavior.
- Yes, I always have the problem.
- No, no toprc system wide or in my home

```
:~$$ stty size
24 84
:~$ echo $COLUMNS
84

```

>  run cat and copy-paste 1234567890 repeatedly until it overflows to the next line; what's the last digit in the initial line, and what's the first digit in the next line?

last digit 4, new digit 5

typescript is attached.
[typescript.txt](https://github.com/gnunn1/tilix/files/1305730/typescript.txt)

> What does echo $TERM report?

`xterm-256color`

> You don't have any screen/tmux running, do you?

No.

It doesn't happen in `gnome-terminal`.

`xterm` is working completely fine.

**Comment by egmontkob** [comment] 2017-09-15 09:00
Probably related: https://bugzilla.gnome.org/show_bug.cgi?id=787710

**Comment by egmontkob** [comment] 2017-09-15 09:01
Can you try `cat typescript` at the same window size? For me it prints `top`'s output correctly; for you I assume it'll be broken again.

Could you then please slowly widen the window? Is there a point where the lines suddenly jump close to each other so that there are no more empty lines in between? What window size is that?

@gnunn1 Can Tilix do geometry hints? I cannot find it suddenly. I'd love to test with that too if available.

**Comment by c0de123** [comment] 2017-09-15 09:10
It is broken. I can widen it and it even gets to a point where the lines line up as expected but 
`stty size `
still says
`24 84`
.
If I get to the point where it is broken again, size is
`24 83`
so somehow the size is reported incorrectly in the beginning?

**Comment by egmontkob** [comment] 2017-09-15 09:15
Ooops... we've got something really nasty going on...

Could you please confirm it, it sounds so unbelievable :)

`stty size` reports a certain size, then you make the terminal wider, and it indeed gets wider by at least one entire cell (not just a few unusable pixels) which you cal tell because it rearranges the contents, and then `stty size` still reports the same size as previously?

Is this your initial window size? What happens if you drag the window border a little bit back and forth and then run `top`, is it perhaps correct then?

**Comment by c0de123** [comment] 2017-09-15 09:31
Again:
I open `tilix`, do an `stty size` and get `24 84`. This is my initial window size.
I do `cat typescript` and get broken lines. I increase the width of the window a few pixels and lines are displayed correctly.
I run `stty size` again and get the same as above, `24 84`.
But `top` is still broken, no matter how I increase the width of the window.
If I stop `top` and then widen the window, the lines I still see in my terminal align, though. So the more I run `top` in the same terminal, the more I will have to widen my window to see the lines aligned.

**Comment by egmontkob** [comment] 2017-09-15 09:43
Thanks a lot!

I'm quite certain it's a nasty bug somewhere in VTE's geometry handling, which, for whatever reason, is triggered by Tilix. I can reproduce some problems, but cannot reproduce your specific one with `top`. I wish I could, that'd make debugging much easier.

I'm off for the weekend now.

**Comment by gnunn1** [comment] 2017-09-15 12:15
@egmontkob Tilix does not use geometry hints, is there something specific you want me to try?

The only other suggestion I have is for @c0de123 to try using the normal scrollbar instead of the scrolled window which is the default. In Preferences | Appearances de-select the option ```Use overlay scrollbars``` and restart Tilix to see if it makes any difference.

**Comment by stullii** [comment] 2017-09-15 12:26
Disabling overlay scrollbars worked for me. Now `top` works without problems!

**Comment by c0de123** [comment] 2017-09-15 15:48
I can confirm that disabling overlay scrollbars actually fixed the problem, on both Debian and Ubuntu.
Thanks.

**Comment by gnunn1** [comment] 2017-09-15 16:02
Thanks, it's interesting to me that I don't see the same issue on Arch, my version of GTK is somewhat newer at 3.22.21

**Comment by egmontkob** [comment] 2017-09-17 19:46
In https://bugzilla.gnome.org/show_bug.cgi?id=760718 it was stated that "GtkScrolledWindow is simply incompatible with VteTerminal."

So, can't we say that Tilix is doing something wrong with this option, at least until this missing feature is addressed?

(I still don't have absolutely any idea how VTE can have an internal contradiction about its own logical size though, which seems to be the case here.)

**Comment by gnunn1** [comment] 2017-09-17 19:52
@egmontkob I was going by this one where it looks like it was enabled in gnome-terminal but maybe that was premature on my part. 

https://bugzilla.gnome.org/show_bug.cgi?id=733210

**Comment by egmontkob** [comment] 2017-09-17 19:56
Haha... yup maybe they thought it was working now but it isn't :D 

We'd need input from Christian and Debarshi, they know a lot about this area, I don't.

**Comment by gnunn1** [comment] 2017-09-17 20:01
I'll probably just change the default to disable the overlay scrollbars by default, issue #733 was also caused by this. It's a pity because it looks 1000 times better then the separate scrollbar IMHO.

**Comment by egmontkob** [comment] 2017-09-18 14:47
@gnunn1 Please don't close this yet. There's a severe issue here to be investigated. I'd perhaps be okay with closing this if you removed the relevant config option entirely. It's not okay to have a boolean preference whose nondefault value causes such misbehavior of `top`.

**Comment by gnunn1** [comment] 2017-09-18 14:54
@egmontkob This only appears to be an issue on Mate DE as far as I can tell which I don't support, I only support Unity and Gnome. I've had the overlay scrollbars as the default option with GTK 3.22 for quite awhile now and this is the first time the issue has come up, likely because Mate is finally catching up GTK version wise.

As far as I can tell, it works perfectly fine on Arch Linux and I like the overlay scrollbars so I'm not removing the option. I'd be happy to modify the text to note it as experimental though.

**Comment by egmontkob** [comment] 2017-09-18 15:02
mate-1.18, released on 2017-03-13 is Gtk+3 only, meaning it uses the very same Gtk+ as the rest of your desktop. If it's still buggy there, the only thing I can think of is the WM doing something nasty. Plus there's definitely something nasty going on in VTE, too.

I guess an "experimental" label could be an ideal solution until we really understand and fix what's going on. Thanks a lot! :)

**Comment by egmontkob** [comment] 2017-09-18 15:12
Good news: I can reproduce the problem on Mate desktop :)

**Comment by f2404** [comment] 2017-09-18 15:13
@egmontkob Does this mean there must be something Mate-specific?

**Comment by c0de123** [comment] 2017-09-18 16:38
It is also a problem on xfce (xubuntu) as far as I can tell.

**Comment by egmontkob** [comment] 2017-09-18 20:24
@f2404 I don't know yet. So far I could only reproduce on Mate desktop, @c0de123 not even on Xfce4.

It's not always buggy for me. Typically the first `top` is okay. Then when I quit and restart it, the second one starts buggy, but sometimes heals itself. Sometimes stays buggy. But at least buggy often enough to be debuggable.

Debugging with `trap 'stty size > /dev/pts/someotherterminal' WINCH` sometimes reports spurious resizes when just pressing Enter at the prompt (it keeps reporting 24 81), sometimes reports a rapid back and forth change (e.g. 24 82 and then 24 81 at each Enter at the prompt).

We should debug the size as reported by VTE itself, not the shell. It's weird when a size change is reported while it hasn't actually changed. Not sure if it's an issue with VTE, or `bash` swallows a quick WINCH. Anyway, it shouldn't cause a problem.

I suspect while `top` is running there are also continuous back and forth resize events. This could pretty much explain why `top` keeps updating the screen without the usual delay of a couple of seconds.

The scrollbar in Xfce4 is really an overlay one, it overlays the rightmost characters. The scrollbar in Mate isn't. It's a "regular" scrollbar to the right of the normal contents. Moreover, if you switch to the alternate screen of the terminal (e.g. run `mc` or `vim`), the scrollbar disappears and the actual usable area of the terminal becomes wider. This shouldn't happen. Similarly: When the window is opened, the scrollbar is not yet present. Accordingly, `stty size` reports a certain size, 24 82 for me. After pressing Enter a couple of times so that the bottom is reached and the scrollbar appears, the VTE widget is narrowed and `stty size` reports a smaller size, 24 81 for me. (Another interesting story is why it's not 24 80 originally... nevermind.)

At this point I much more suspect an issue with the default Gtk+ theme of Mate, rather than VTE. (And, of course, there might be non-broken themes for Mate, and broken themes for Xfce and others as well, who knows.) Its scrollbar should never change its width that is additional to VTE's width (it's okay to change the width that's overlaid), not even when it decides the contents fully fit and hence there's no need to display the scrollbar.

Looks to me now that most likely VTE has a consistent notion of its size at any given moment, it just changes unexpectedly and frequently due to the craziness the scrollbar does.

The initial size being different from 80x24 is probably a separate issue, and is probably the same as the aforementioned GNOME [787710](https://bugzilla.gnome.org/show_bug.cgi?id=787710).

Does any of you guys feel like filing a bug against Mate's default Gtk+ theme?

**Comment by egmontkob** [comment] 2017-09-19 12:17
@gnunn1 If it's indeed a problem with the Gtk+ theme then I think you're absolutely fine without the "experimental" label, you could even revert the change I guess.

**Comment by gnunn1** [comment] 2017-09-19 12:39
So in Mate if you change the GTK theme to Adwaita it works fine?

**Comment by egmontkob** [comment] 2017-09-19 12:46
In System -> Preferences -> Look and Feel -> Appearance there are about a dozen themes to choose from (no Adwaita), all have this faulty scrollbar and hence faulty Tilix behavior. I guess I'd have to change it somewhere else, not sure if Mate allows that.

**Comment by gnunn1** [comment] 2017-09-19 12:49
In gnome-terminal, try this to force the Adwaita theme (with tilix not running). Adwaita is bundled with GTK AFAIK so it should be available.

```
GTK_THEME=Adwaita tilix
```

**Comment by egmontkob** [comment] 2017-09-19 12:59
Still buggy.

I have, however, noticed a `GTK_OVERLAY_SCROLLING=0` in the environment. Unsetting this causes the terminal to open and remain at 80x24 and the scrollbar indeed overlais the contents and no bug occurs with `top`.

I'm wondering, maybe as a workaround Tilix could check for this env variable, and if set to 0, do as if its "Use overlay scrollbars" config option was disabled. Does this make sense? Or the other way around: just unset this env var?

**Comment by egmontkob** [comment] 2017-09-19 13:01
Oh, and by the way, by manually exporting `GTK_OVERLAY_SCROLLING=0` the bug is reproducible in Unity7, and presumably any other window manager / desktop environment as well.

**Comment by gnunn1** [comment] 2017-09-19 13:07
Great catch, I can reproduce it with ```GTK_OVERLAY_SCROLLING=0``` here as well. I think you are correct, tilix should check for this environment variable and when set not use the overlay scrollbars in this situation nor surface the option to enable it.

I'll make this fix and then revert my other changes where I made the default false instead of true and the experimental tag.

**Comment by egmontkob** [comment] 2017-09-19 13:11
In the mean time I'm wondering whose fault it is after all :) Maybe the existence of `GTK_OVERLAY_SCROLLING` is conceptually broken. It takes a scrollbar that was designed to be overlaid and as such its width potentially varies over time, and places it next to the widget, causing the widget to also repeatedly change its width.

**Comment by gnunn1** [comment] 2017-09-19 13:31
It's a new environment variable to me, can you tell when this variable is set that the reported allocated width includes the scrollbar? Off-hand I'd say it's a GTK issue but don't know enough about the low level details to say for sure.

**Comment by egmontkob** [comment] 2017-09-19 13:40
It's new to me too, I don't know anything about it. I have no clue if you can query Gtk+ about its actual current behavior wrt. the scrollbar, I was thinking about checking the env var itself (querying Gtk+ would be nicer of course).

**Closed** 2017-09-24 16:15 UTC
Labels: bug, Upstream

**Comment by gnunn1** [comment] 2017-09-24 16:16
Tilix will not check for the ```GTK_OVERLAY_SCROLLING``` and if set to 0 will disable the option to use scrolledwindow and use the scrollbar instead.

Thanks again @egmontkob for your help with this.

**Comment by egmontkob** [comment] 2017-09-24 19:38
I guess you meant "Tilix will no**w** check..." ;) Thanks for this workaround!

**Comment by gnunn1** [comment] 2017-09-24 19:40
I did, oops :)
