### ISSUE TITLE
tilix-nautilus doesn’t work anymore in Fedora 27

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1278] opened 2018-01-30 14:13 UTC
Pretty strange… In my older system is works fine since F26, but in two freshly installed F27 VMs, I got no Tilix context menu (whereas gnome-terminal-nautilus works fine when (un)installing).

**Comment by gnunn1** [comment] 2018-01-30 19:12
At a command line, if you run ```nautilus -q``` to close it and then run ```nautilus``` again, what is the output that is shown?

**Comment by fbruetting** [comment] 2018-01-31 14:40
Hi Gerald, here’s the output (there’s absolutely no output with this package not installed):
```
$ nautilus
ImportError: could not import gobject (error was: 'No module named gi._gobject')

(nautilus:28062): Nautilus-Python-WARNING **: pygobject initialization failed

(nautilus:28062): Nautilus-Python-WARNING **: nautilus_python_init_python failed
```

**Comment by storm119** [comment] 2018-02-02 11:16
Tilix depend on python2-nautilus for open "context menu" to works correctly on Nautilus [correct me if I'm wrong]...but prior installing the python2-nautilus, one need to uninstall the python-nautilus (current version conflicting with python2-nautilus atleast it's happen on my box running Manjaro Arch) 

@gnunn1 any chances Tilix will use/integrating with python-nautilus instead of python2-nautilus or make it to work with nautilus-python3 ?

TIA

**Comment by phw** [comment] 2018-02-02 11:25
> any chances Tilix will use/integrating with python-nautilus instead of python2-nautilus or make it to work with nautilus-python3 ?

Actually it should already work with python3, see https://github.com/gnunn1/tilix/issues/1252 . Which version of Tilix is this?

**Comment by storm119** [comment] 2018-02-02 13:02
> Actually it should already work with python3, see #1252 . Which version of Tilix is this?

Alrite....my mistake ditched python2-nautilus and rebuild/reinstall Tilix solved my issue...version 1.7.5 btw

**Comment by gnunn1** [comment] 2018-02-03 00:27
So is this an issue with the waytilix is packaged in COPR or did you install tilix manually?

**Comment by fbruetting** [comment] 2018-02-03 22:26
I installed it right out of the dnf repo (v1.7.5-1).

**Comment by gnunn1** [comment] 2018-02-03 23:14
@fbruetting I think you should open a bug report against that then since this sounds like a package issue to me. If that makes sense to you then please link this issue to that when you do so.

**Comment by ykgmfq** [comment] 2018-02-07 09:59
Works fine for me, cannot reproduce.

```
$ dnf list installed|grep tilix
tilix.x86_64                         1.7.5-1.fc27               @updates        
tilix-nautilus.x86_64                1.7.5-1.fc27               @updates
```

**Comment by cra0zy** [comment] 2018-02-07 22:45
I was able to reproduce it, but looking at the error it seems like the dependency was not getting installed, to fix it run: `sudo dnf install pygobject3 python3-gobject`

**Comment by gnunn1** [comment] 2018-02-10 02:04
I'm closing this as it is not a tilix issue but rather a packaging issue.

**Closed by gnunn1** 2018-02-10 02:04 UTC

**Comment by ykgmfq** [comment] 2018-02-10 13:50
[downstream bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1539039)

**Comment by fbruetting** [comment] 2018-02-10 13:52
Thanks! Just right now, I was searching for the packager… ^^

**Comment by fbruetting** [comment] 2018-02-10 13:54
@gnunn1 Will it be possible to ship Tilix via flatpak? I know the sandbox thing won’t work, but still it would be more convenient.

**Comment by gnunn1** [comment] 2018-02-10 14:08
Yes it is and I think the work is done with respect to fixing the sandbox, it's just a matter of time. If someone wants to volunteer to maintain the flatpak so I don't have to then that would be great.

**Comment by gombosg** [comment] 2018-08-21 09:27
Still not fixed in Fedora. :(

**Comment by cra0zy** [comment] 2018-08-21 10:51
`sudo dnf install pygobject3 python3-gobject`

**Comment by gombosg** [comment] 2018-08-21 12:03
Yes, thanks, I saw it above and fixed for myself already. I mean, the package dependency is not fixed. :)

**Comment by bilelmoussaoui** [comment] 2018-08-21 12:50
@gombosg  It was reported to Fedora packagers see https://bugzilla.redhat.com/show_bug.cgi?id=1539039
