### ISSUE TITLE
Terminix in quake mode does not focus

### ISSUE THREAD

**Issue by Kozzi11** [gnunn1/tilix#818] opened 2017-03-07 06:08 UTC
When running terminix in quake mode it does not focus, so I must click on terminal be able to write anything. It happens mainly with first start of terminix in quake mode

**Comment by gnunn1** [comment] 2017-03-08 15:03
Is this on X11 or Wayland? Also, what distro and version are you using? Finally what version of terminix are you using.

**Comment by gnunn1** [comment] 2017-03-11 18:28
@Kozzi11 Any responses to my questions, otherwise I'm going to close this issue.

**Comment by repsac-by** [comment] 2017-03-11 19:23
@gnunn1 X11 and Wayland with GDK_BACKEND=x11

After first launch has no focus, but after calling an already running instance works correctly.

**Comment by Kozzi11** [comment] 2017-03-11 20:04
@gnunn1 Sorry, I somehow missed your first response, which is wierd, because even github does not remind me :). It does not matter, which distribution or wayland vs. X11. I am using Arch, Fedora .... It happens on all of them. But on Fedora it seems worse. It happens with almost every open.

**Comment by gnunn1** [comment] 2017-03-12 01:39
I'm not able to reproduce on Arch as it is working fine for me as far as I can tell. Are you using the version from master or 1.5.2?

**Comment by GreenDou** [comment] 2017-03-12 15:15
Versions
	Terminix version: 1.5.2
	VTE version: 0.42
	GTK Version: 3.18.9

Also has this issue. Quake mode never focus automatically. But it focus without --quake.

**Comment by gnunn1** [comment] 2017-03-12 17:43
I just tried it in Fedora 24 as well, works fine for me there as well. Having said that I've checked in a change to try to help with this so feel free to build it and see how it goes.

**Comment by repsac-by** [comment] 2017-03-12 18:42
@gnunn1 focusing is influenced by the option `Set hint for window manager to disable animation`
if not checked then focused otherwise no focus

**Comment by gnunn1** [comment] 2017-03-12 21:57
@repsac-by Thanks, that does indeed seem to be the problem. I'll probably remove the option if it's causing this issue.

@Kozzi11 and @GreenDou Can you confirm if you have this option enabled?

**Comment by Kozzi11** [comment] 2017-03-13 09:30
@gnunn1 Yes, I can confirm that

**Comment by gnunn1** [comment] 2017-03-13 12:20
I've removed the disable animation option to fix this issue.

**Closed** 2017-03-13 12:19 UTC
Labels: bug, Can't Reproduce
