### ISSUE TITLE
Issue on focus re-capturing in Quake mode in Xfce

### ISSUE THREAD

**Issue by y-usuzumi** [gnunn1/tilix#1041] opened 2017-08-03 04:11 UTC
Hi! Not sure if it's an issue with Tilix, but in Quake mode, if I open any dialog, e.g. preferences or rename session, then close the dialog, Tilix loses its focus. Have to click on the window again to get focus.

This is not the case for Tilix in normal mode, also not the case in GNOME Shell.

**Comment by gnunn1** [comment] 2017-08-03 12:38
It works fine for me in Gnome, maybe it's an issue specific to XFCE? Unfortunately I do not support XFCE, only Gnome and Unity, in the sense of trying to reproduce issues in that environment as I need to keep things manageable. 

As a result I'm closing this issue, however I would suggest trying to reproduce it with the XFCE terminal in it's drop-down mode, if you can open a bug with them.

**Closed by gnunn1** 2017-08-03 12:38 UTC

**Comment by manlito** [comment] 2020-02-13 03:01
I can confirm this happens in xfce 4.14.1. Tried different settings on xfce nothing seemed to work. I found the issue to be caused by:
```
setSkipTaskbarHint(true);
setSkipPagerHint(true);
```
In [AppWindow constructor](https://github.com/gnunn1/tilix/blob/1.9.3/source/gx/tilix/appwindow.d#L1691-L1692). Simply changing both to false or commenting those fixes the issue. Given no else is having this issue, I suspect it could be a matter of specific setups and GTK (for instance, I do use Picom). Let me know if you need more experiments @gnunn1 , great code, thank you!
