### ISSUE TITLE
Using xorg, unable to type tilda (~) when quake mode mapped to grave (`)

### ISSUE THREAD

**Issue by computorist** [gnunn1/tilix#1188] opened 2017-11-14 14:09 UTC
```
╰╴► echo $XDG_SESSION_DESKTOP 
gnome-xorg

╰╴► gnome-shell --version
GNOME Shell 3.26.2

╰╴► tilix --version
Versions
	Tilix version: 1.7.1
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=1
	Badges enabled=1
```
Using tilix within xorg and have the grave character, `, assigned to quake mode. Works great!
But, it prevents me from typing a tilda character, ~.

For example, typing ~ with a non-quake terminal the cursor flashes but not character is emitted. Typing a ~ within tilix's quake terminal closes the terminal.

I'm continuing to use tilda for my drop-down terminal but would like to unify all terminals under tilix.

**Comment by f2404** [comment] 2017-11-14 14:52
Well, it shouldn't be a surprise that a hotkey press will be swallowed by the program and not propagated further, right?

**Comment by gnunn1** [comment] 2017-11-18 15:41
Unfortunately I cannot reproduce when I try it with Gnome. I map the hotkey to the grave character in Gnome's keyboard applet, and tilix displays as expected when I press the grave key. I type the tilda character into the tilix window using shift-grave and it enters as expected. I'm running the same GTK version as you are.

Any chance you are using an international keyboard or something different on that front?

**Comment by computorist** [comment] 2017-11-22 13:49
Nothing funky; clean Arch linux install on a ThinkPad T440s. I'll try and find time to pick at it a bit more. 
Thanks

**Comment by gnunn1** [comment] 2017-12-21 18:15
Are you still having this issue?

**Comment by computorist** [comment] 2017-12-22 15:31
Yes. Just tried again. Updated to latest version:
```
╰╴► tilix --version
Versions
	Tilix version: 1.7.3
	VTE version: 0.50
	GTK Version: 3.22.26

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by Moulick** [comment] 2018-01-06 16:38
Hey, I am having the saming issue, I can't type ~ when mapped ` to tilix --quake . I am running Gnome 3, Ubuntu 17.04 on Xorg

![screenshot from 2018-01-06 21-59-07](https://user-images.githubusercontent.com/15780903/34641625-e444d020-f32c-11e7-90d6-d638c5d7f84a.png)

![screenshot from 2018-01-06 22-01-48](https://user-images.githubusercontent.com/15780903/34641686-dde42450-f32d-11e7-8f95-4afaf4413d11.png)

Also getting this other error 

`** (tilix:14610): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

**Comment by Moulick** [comment] 2018-01-16 17:01
Also this problem is not present in Guake

**Comment by gnunn1** [comment] 2018-01-27 21:13
Is anyone having this issue using xdb to map the grave key to something else? I'm wondering if this is related to #1273

**Comment by computorist** [comment] 2018-05-21 20:56
Following up ... This issue is no longer happening. I'm able to use tilix in quake mode and type tilda characters.
```
╰╴► tilix --version
Versions
	Tilix version: 1.7.9
	VTE version: 0.52
	GTK Version: 3.22.30

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=1
```

**Comment by gnunn1** [comment] 2018-05-21 21:01
Thanks, I'll close the issue but if it happens again feel free to re-open.

**Closed by gnunn1** 2018-05-21 21:01 UTC
Labels: Can't Reproduce, bug

**Comment by Moulick** [comment] 2018-05-21 21:11
@computorist how did you solve this issue, simple tilix update ?

**Comment by computorist** [comment] 2018-05-22 17:28
@Moulick Nothing intentional. I've been using tilda for a quake like terminal since the issue was found. Yesterday I decided to try tilix again and it now works. 

Could be latest tilix release or (more likely) the upgrade to the latest gnome environment for me.

Sorry, not very helpful.
