### ISSUE TITLE
alt+shift+<arrow> crashes tilix if no other terminal is available

### ISSUE THREAD

**Issue by schiessle** [gnunn1/tilix#1472] opened 2018-07-13 14:48 UTC
By default you can use `alt+shift+<arrow>` to resize the terminals.

E.g. if I first create two terminals next to each other with ctrl+alt+r I can use alt+shift+right and alt+shift+left to resize the two terminals. But if press alt+shift+down or alt+shift+up and there are no terminals above each other tilix crashes with a segmentation fault. Same if I started tilix with just one terminal and press alt+shift+right for example. This way I already crashed tilix with multiple terminals and session multiple times by accident.

I'm running tilix 1.7.9 on Debian sid.

**Comment by gnunn1** [comment] 2018-07-13 22:39
I think thiis is a duplicate of #1418

**Comment by gnunn1** [comment] 2018-07-15 14:15
I can't reproduce this, pretty sure this has been fixed already as per previous comment.

**Closed by gnunn1** 2018-07-15 14:15 UTC
