### ISSUE TITLE
Text is blurry when using a background image

### ISSUE THREAD

**Issue by thomasave** [gnunn1/tilix#1611] opened 2018-12-28 21:46 UTC
Setting any background image results in the terminal text becoming blurry.
In the first image you can see htop running in Tilix without using a background image. 
In the second image nothing is changed except for setting the background image.
(not even the transparancy)
![screenshot from 2018-12-28 22-32-58](https://user-images.githubusercontent.com/8020909/50528869-2a9f7480-0af1-11e9-91e3-334338d36459.png)
![screenshot from 2018-12-28 22-33-29](https://user-images.githubusercontent.com/8020909/50528876-2f642880-0af1-11e9-930b-a70abcc6a7a1.png)

I'm using Tilix 1.8.5 on Arch Linux.

**Comment by gnunn1** [comment] 2018-12-30 15:21
I am not able to reproduce it, what font are you using in the terminal? Also what desktop environment?

**Comment by thomasave** [comment] 2019-01-01 14:58
I'm using the `Ubuntu Mono derivative Powerline Regular` font from https://github.com/powerline/fonts in the GNOME desktop environment.
I also tried it on my laptop, using the same fonts, distro and desktop environment, and I also can't reproduce the problem unfortunately.

**Comment by gnunn1** [comment] 2019-01-02 13:21
Are you using any sort of scaling (gnome, font, etc) on the machine where this happens?

**Comment by thomasave** [comment] 2019-01-02 14:45
Good catch! It seems to happen when enabling 2x scaling in `gnome-control-center`.

**Comment by gnunn1** [comment] 2019-01-02 23:31
This has been fixed by creating a similar surface from the existing cairo context rather then a brand new surface which presumably did not inherit the scale factor.

**Closed** 2019-01-02 23:30 UTC
