### ISSUE TITLE
Distorted tabular output with `tabs -4`

### ISSUE THREAD

**Issue by fbruetting** [gnunn1/tilix#1616] opened 2019-01-02 12:54 UTC
`Tilix x1.8.3-Flatpak`

For having consistent 4-spaces-wide tabs, I put `tabs -4` in my `.bashrc`. This however led to quite some console programs showing distorted tabular output. Here are some screen shots. Additionally, in `htop` sometimes strokes of the load bars stay visible when the bar shrinks.

![bildschirmfoto von 2018-12-08 19-23-21](https://user-images.githubusercontent.com/10520767/50592676-6b064600-0e95-11e9-8bf8-95b7660ac60e.png)
![bildschirmfoto von 2018-12-30 19-46-48](https://user-images.githubusercontent.com/10520767/50592677-6b064600-0e95-11e9-8a03-d6378ae18649.png)
![bildschirmfoto von 2019-01-02 12-54-19](https://user-images.githubusercontent.com/10520767/50592778-dcde8f80-0e95-11e9-8b66-2f72d984d777.png)

**Comment by gnunn1** [comment] 2019-01-02 13:18
That is probably an issue with VTE, do you see the same behavior in gnome-terminal? If no, does disabling the overlay scrollbars make any difference?

**Comment by egmontkob** [comment] 2019-01-02 14:15
What's the version of VTE (`echo $VTE_VERSION`)? I can easily imagine an older version that doesn't yet support the REP sequence. (I can't reproduce the problem.)

**Comment by fbruetting** [comment] 2019-01-07 23:04
Yes, Gnome Terminal also has this issue. VTE version is 5402.

**Comment by egmontkob** [comment] 2019-01-08 09:00
Okay, it's not a REP issue then.

How about `xterm`, is the bug present there? If xterm is also buggy then it's probably a bug in ncurses.

Assuming that in xterm it works fine:

What does `echo $TERM` say?

The bottom half of htop's window is also faulty, columns are not aligned up properly. This one I believe is easier, quicker to reproduce than the red bar, so let's focus on this one.

Could you please start `script`, then start `htop`, then as soon as you see the faulty layout press `q` to quit (hopefully after the initial paint of htop's screen), then type `exit` to quit script. It notifies you that a file called `typescript` was created, please attach it, thanks!

**Comment by fbruetting** [comment] 2019-01-08 21:53
Here please:

```
> echo $TERM
xterm-256color
```

[typescript.zip](https://github.com/gnunn1/tilix/files/2738548/typescript.zip)

Stupid GitHub doesn’t allow raw data or .txz, don’t you want to move to GitLab? 🤪

**Comment by egmontkob** [comment] 2019-01-08 23:06
Thanks!

Here's what I can see so far:

The second line of typescript begins with setting the tab positions at every 4th column, before you type anything. Looks like you've connected up `tabs -4` to your .bashrc or prompt_command or alike, that's okay. `htop`'s output is line 3 of the file.

I forgot to ask you to record the window size, it's 93x29. I'm playing back with `slowcat -t 10000 typescript`, slowcat is inside VTE's source tree.

The screen is painted twice. In the first run, the "11400 frank 20 ..." line (the one below the cyan highlighted line) is faulty. At this and only this place, after "11400 frank" (11 characters, the cursor is now in column 12) typescript contains a literal TAB character, followed by a space and then "20". Clearly ncurses expects this TAB to advance the cursor to column 17, but instead it advances it to column 13.

The screen is painted a second time too, then this "20" remains there because the cursor is moved to an explicit column beyond this position. ncurses believes there's nothing and skips it. It's fine, this is not a bug, it's just that the previous bug remains visible.

Replaying the same file in `xterm` also produces the same broken result.

There seems to be nothing about ncurses setting or querying tab positions. Well, xterm doesn't seem to support the "tab stop report (DECTABSR)" escape sequence and VTE doesn't support it either, so it can't be queried. I didn't see any sign of trying to query it indirectly (e.g. by emitting a TAB and querying the cursor position) either; again, the only time a TAB is emitted is when the display gets broken, there's clearly no querying there.

Are you absolutely sure that you cannot reproduce this bug in `xterm`, with the same `TERM=xterm-256color` setting, and of course after executing `tabs -4`? If indeed that's the case then ncurses figures out by some other magic whether it's talking to an xterm or a VTE and behaves differently in these cases, which would be quite ugly.

Anyway, in either case, it clearly doesn't look like a VTE bug. VTE does what it's instructed to do, and xterm also produces incorrect rendering if given the same output to replay.

I believe you should report to ncurses that it shouldn't rely on a particular hardcoded tab width if the terminal emulator allows to redefine tab stops from the initial value (as in terminfo's "it" field). Practically, I think it shouldn't ever emit the TAB character. (As a side note, VTE has some magic to preserve TAB characters under certain circumstances when copy-pasting. Even if ncurses could detect the tab width, emitting TABs could result in inconsistent copy-pasting experience in VTE.)

For future reference, what's your distro and ncurses version? I'm on Ubuntu 18.10, ncurses 6.1+20180210, and I still couldn't reproduce the issue. Although, obviously, I have different user names and such. I have no idea what logic makes ncurses emit a TAB here and here only. Maybe if my username was 5 letters long and had the same processes you do, I could also reproduce it, dunno.

**Comment by fbruetting** [comment] 2019-01-13 21:12
I’m quite confused. Am I not using xterm when `xterm-256color` is shown to me?

I’m using Fedora 29 Silverblue, and `ncurses-6.1-8.20180923.fc29.x86_64`.

You can let it run for a short time, it here-and-there will produce corrupted output.

**Comment by egmontkob** [comment] 2019-01-13 21:41
By xterm I meant the terminal emulator application called `xterm` instead of `tilix`.

**Comment by fbruetting** [comment] 2019-01-13 23:41
```
> echo $TERM
xterm-256color
```

![bildschirmfoto von 2019-01-13 23-52-56](https://user-images.githubusercontent.com/10520767/51092210-13b97d00-1795-11e9-92c9-9f2dc39ad583.png)

**Comment by egmontkob** [comment] 2019-01-14 00:54
Yes please, looks like an ncurses issue to me.

**Comment by gnunn1** [comment] 2019-01-31 23:14
I'm closing this as this does not appear to be an issue with Tilix.

**Closed by gnunn1** 2019-01-31 23:14 UTC
