### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by EmTee70** [gnunn1/tilix#1132] opened 2017-09-25 13:06 UTC
When I am splitting the terminal at first vertically, I don't find a way to add an horizontal sub-terminal spreading from left to write (I only get a small one inside of 2).

How to klick to get there:

```
|-----------------|-------------------|
|                 |                   |
|        1        |          2        |
|                 |                   |
--------------------------------------
|                3                    |
--------------------------------------
```

**Comment by gnunn1** [comment] 2017-09-25 14:59
Duplicate of #1131

**Closed by gnunn1** 2017-09-25 14:59 UTC
