### ISSUE TITLE
Special Input for synchronized input

### ISSUE THREAD

**Issue by iax7** [gnunn1/tilix#1174] opened 2017-11-02 17:31 UTC
When having multiple terminals the synchronized input is very handy, but there are sometimes when there is a need to type something different in each terminal, as example, I have 6 terminals:
![image](https://user-images.githubusercontent.com/6983510/32340623-bf430fde-bfc0-11e7-955e-c1125c34d127.png)
If I need to specify a different host for each I need to disable synchronization, type individually, and re-enable synchronization. This could be easily achieved if tilix has a special input window and you can type something like this:
```
1:host1
2:host2
3:host3
4:host4
5:host5
6:host6
```
where `#:` would be the terminal number, and the `host#` would be the actual input.
![image](https://user-images.githubusercontent.com/6983510/32340742-12c02ea8-bfc1-11e7-993a-46cd44a71831.png)

This is a simplified example, the actual use case is for different hosts with names not that simple.

**Comment by egmontkob** [comment] 2017-11-02 22:15
(I'm not a Tilix developer, just randomly commenting.)

In case you would type that "1:host1 2:host2" right there into a special window, I don't think it's that useful.

Currently you can define a hotkey for toggling Synchronized input, press that to temporarily disable synchronization, type the hostnames one by one, using Alt+arrows (or whatever other shortcut) to navigate through panes. It's relatively quick and convenient, plus you get immediate feedback that you're doing it right.

A separate popup would not only require additional work from Tilix, but IMO would hardly (if at all) make this use case more convenient. You get a text entry box; how do you remember what the separator is, what if you make a syntax error, don't list all the terminal numbers, list one multiple times etc. No help, no immediate feedback. Even if Tilix presented a window with multiple one-liner text entries, one for each (and the terminal numbers would be shown outside of these text entry fields), you'd still have to mentally perform the mapping of how the 2x3 terminals laid out in a grid are now enlisted in a single table of 6 rows. You'd hardly (if at all) save on typing, plus would have no feedback until the end whether you're doing it right.

Terminator has an option to inject the terminal number into each pane (that is, a different number into each). This could be combined with a wrapper shell script in front of ssh (or, for this particular use case, host aliases set up in advance) if Tilix also had such an option.

Another approach that I'd find viable and worth consdiering would be not to type those different strings right there into a popup, but to have them defined in Tilix's configuraiton in advance. You could create as many lists as you wanted, each bearing a name that you specify and as many entries as you wish. There would be a drop-down where Tilix lists all these names (e.g. "hostnames", "dev hosts", "qa hosts", "favorite drinks" whatever) (perhaps with the number of entries for each list in parentheses) and you could pick one to inject. Tilix could then probably present a confirmation dialog if the number of entries in that list isn't equal to the number of panes currently in synchronized more, to confirm that the last few entries won't be injected anywhere, or that some synchronized terminals won't receive any input. If confirmed, or if the number of the entries matches, it'd inject them, one to each pane.

**Comment by gnunn1** [comment] 2017-11-02 22:18
Tilix has a command to insert the terminal number, you just need to assign a shortcut to it.

**Comment by egmontkob** [comment] 2017-11-02 22:28
Oh, I missed it. (Does it have a menu entry too? I still can't find it. Or is a shortcut the only way to go?)

**Comment by gnunn1** [comment] 2017-11-02 22:52
Just a shortcut, there's too many commands to make everything a menu item unfortunately.

![screenshot from 2017-11-02 18-52-15](https://user-images.githubusercontent.com/9358238/32354190-fbab7c52-bffe-11e7-9485-c83f04b07a3d.png)

**Comment by iax7** [comment] 2017-11-02 23:44
I guess you missed my last paragraph, I'll paste it again for convenience:

**This is a simplified example, the actual use case is for different hosts with names not that simple** (and non-consecutives, not even numbers)

I made a mistake by simplifying it with an example covered by another feature. But as I said, the use case is not that simple. I thought that another window where you can paste plain text and edit there would be easier without leaving the keyboard.

How would you resolve to make a quick unique input to several terminal windows?

P.S @gnunn1 I agree that _insert terminal number_ feature is somewhat hidden.

**Comment by iax7** [comment] 2017-11-02 23:56
Actual use case: 
You need to run almost same commands to a couple of servers, and you have a list of the hosts:
```
lnx02abc
unx12xyz
slc00qws
... and so on
```
when you don't have this on top of your head you need to disable the synchronization, copy each line, and paste in every window... that's why I thought about a window to paste that list that I already have and just tell the tool where to paste it (the `#:` part)

you can say, those hostnames are not that difficult, but what if the list contains longer strings, like complex IDs?

I think this would be a killer feature.

**Comment by egmontkob** [comment] 2017-11-03 00:07
With this additional requirement that one should be able to copy-paste all the values (newline separated) in a single step (a totally counterintuitive UI for most people), I don't share your view of this being a killer feature. My humble guess is that this feature would be so marginal that probably hardly anyone (if anyone at all apart from you) would use it. I might be wrong of course, and YMMV.

On the other hand, you can could easily create a shell script that prints the Nth host, and then in Tilix do `ssh $(get-Nth-hostname [here comes the magic hotkey to inject the terminal's number])`

**Comment by iax7** [comment] 2017-11-03 01:07
@egmontkob please explain why you think that UI is counterintuitive?

your solution is great for the use case that I used as an example. But again, it has multiple use cases, think you are in 6 different ssh sessions, where that script and/or that file doesn't exist. That's why my initial thought was a client-side solution, in the terminal emulator.

Yes, I know its use is not that common but is those features that are heaven sent when needed.

**Comment by gnunn1** [comment] 2017-11-03 01:12
I tend to agree with @egmontkob on this one, a separate window for input just feels kludgy to me. I'm not seeing the benefit over simply disabling input synchronization, go to each terminal in turn and type in the command directly and then re-enabling input sync. Not enough for anyway for me to want to code this as a feature.

**Comment by egmontkob** [comment] 2017-11-03 10:05
I think I've outlined it before. If it's a regular multi-line text entry field: What's the syntax? Do I need to prefix the lines with "1:", "2:" etc. or not? What's the separator, newline or whitespace? What if the number of entries I type doesn't match the number of panes? Given some weird layout of panes, how do I know which line will correspond to which pane? If I need to use the same list of entries over and over again, would I need to type (or copy-paste) them all over, or would Tilix offer some means of saving/loading them; and if so, how exactly?

I understand that this would be a "heaven sent" feature for you, I don't understand why you think it would be the same for many other people. Terminal emulators are generally not the right place for such features, shell scripting is, as that's by design the most modular part (the "Lego" of Unix systems) where you have the flexibility to implement such convenience tools.

**Comment by phw** [comment] 2017-11-03 10:29
I actually have this case frequently, but I would not use that separate input feature. I would need to open a separate input field somehow, enter all the values I need in some syntax I need to remember (also taking care of terminal number) and submit it, likely double checking in the terminals if it is all ok. It ads all kinds of complications, without helping me in the part that is actual work: typing all the different values. Does not seem to save me any time.

The current approach works well for me:

1. Type everything that is the same with input synchronization enabled
2. Disable input synchronization with hotkey
3. Jump through each terminal and type the different value (I directly see where I am)
4. Enable input synchronization with hotkey and finish the command

**Comment by gnunn1** [comment] 2017-11-04 17:23
I'm going to close this, as discussed I don't think this is useful enough over the alternatives.

**Closed by gnunn1** 2017-11-04 17:23 UTC
Labels: enhancement
