### ISSUE TITLE
-e option results in some directory problem in splitting terminal

### ISSUE THREAD

**Issue by nicmus** [gnunn1/tilix#1378] opened 2018-04-18 08:42 UTC
I am not sure if it is a bug or a intended behaviour. 
Anyway these are the steps that bring to the problem.

open a terminal
cd to a folder (say cd /a/b/c)
run: tilix -e 'vi file.ext' 
    vi opens correctly in a new tilix app
    now if tilix terminal is split, the working directory of the new terminal is the root /
    and no longer /a/b/c

**Comment by gnunn1** [comment] 2018-04-19 00:28
Does it only happen with the -e option? i.e. if you do the following:

1. Open tilix
2. cd to a different directory other then home
3. Split the terminal
4. Is the new terminal directory the same as the previous one or back on home?

If the new terminal is not the same as the previous one, you do not have a properly configured VTE. See this link for more information:

https://gnunn1.github.io/tilix-web/manual/vteconfig/

**Comment by nicmus** [comment] 2018-04-19 04:58
This happens exclusively with -e option.

Some further info:
After running a new tilix with -e option, the first terminal has correct PWD i.e. the one inherited from where tilix -e was invoked. Splitting successively the first terminal results in the abovementioned behaviour.

**Comment by gnunn1** [comment] 2018-04-28 13:36
I cannot reproduce this in master, my attempt to reproduce as follows:

a. ```cd Development/dlang/tilix"
b. In gnome terminal, ```tilix -e "vi dub.json"```
c. Split the terminal, still in ```Development/dlang/tilix```
d. Click on the terminal vi, split it again
e. Split the terminal, still in ```Development/dlang/tilix```

This seems like the expected behavior. Generally problems with PWD indicate VTE is not configured correctly but you said you already confirms it works when not under ```-e```. It's possible I have fixed this inadvertently when correcting another issue. I'll be pushing out a new version this weekend so I would suggest testing that to see if there is any change from your perspective.

**Comment by gnunn1** [comment] 2018-06-23 16:47
I'm going to close this, I cannot reproduce and suspect it's an issue with the users VTE configuration. If you disagree feel free to re-open.

**Closed by gnunn1** 2018-06-23 16:47 UTC
Labels: Can't Reproduce, bug
