### ISSUE TITLE
Cannot set shortcuts with Tab key in config window

### ISSUE THREAD

**Issue by kronos29296** [gnunn1/tilix#1082] opened 2017-08-18 18:57 UTC
I tried to set Ctrl Tab and Shift Ctrl Tab to change sessions in the config window but it did not work.
The keys were not captured at all. I had to use dconf to set the shortcuts.

I have installed Tilix version 1.6.4 in Manjaro Linux from AUR.

**Comment by gnunn1** [comment] 2017-08-18 19:59
Duplicate of #890, unfortunately the GTK shortcut widget doesn't support setting tab.

**Closed by gnunn1** 2017-08-18 19:59 UTC
