### ISSUE TITLE
Feature: Allow tab/session renamming on double click

### ISSUE THREAD

**Issue by mrjk** [gnunn1/tilix#1355] opened 2018-03-29 03:24 UTC
I'm not sure if it is a bug or a feature, but it would be nice if we could rename tabs and sessions with a double click.

Edit: Very similar to #1162

**Comment by gnunn1** [comment] 2018-03-31 17:08
Yes, this is a duplicate of #1162.

**Closed by gnunn1** 2018-03-31 17:08 UTC
